# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /path/to/asterix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /path/to/asterix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /path/to/asterix/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /path/to/asterix/CMakeFiles /path/to/asterix//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /path/to/asterix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named asterix_shared

# Build rule for target.
asterix_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asterix_shared
.PHONY : asterix_shared

# fast build rule for target.
asterix_shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/build
.PHONY : asterix_shared/fast

#=============================================================================
# Target rules for targets named asterix_static

# Build rule for target.
asterix_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asterix_static
.PHONY : asterix_static

# fast build rule for target.
asterix_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/build
.PHONY : asterix_static/fast

#=============================================================================
# Target rules for targets named asterix_exe

# Build rule for target.
asterix_exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asterix_exe
.PHONY : asterix_exe

# fast build rule for target.
asterix_exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_exe.dir/build.make CMakeFiles/asterix_exe.dir/build
.PHONY : asterix_exe/fast

#=============================================================================
# Target rules for targets named test_category

# Build rule for target.
test_category: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_category
.PHONY : test_category

# fast build rule for target.
test_category/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_category.dir/build.make tests/cpp/CMakeFiles/test_category.dir/build
.PHONY : test_category/fast

#=============================================================================
# Target rules for targets named test_dataitem

# Build rule for target.
test_dataitem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dataitem
.PHONY : test_dataitem

# fast build rule for target.
test_dataitem/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_dataitem.dir/build.make tests/cpp/CMakeFiles/test_dataitem.dir/build
.PHONY : test_dataitem/fast

#=============================================================================
# Target rules for targets named test_utils

# Build rule for target.
test_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_utils
.PHONY : test_utils

# fast build rule for target.
test_utils/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_utils.dir/build.make tests/cpp/CMakeFiles/test_utils.dir/build
.PHONY : test_utils/fast

#=============================================================================
# Target rules for targets named test_dataitembits

# Build rule for target.
test_dataitembits: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dataitembits
.PHONY : test_dataitembits

# fast build rule for target.
test_dataitembits/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_dataitembits.dir/build.make tests/cpp/CMakeFiles/test_dataitembits.dir/build
.PHONY : test_dataitembits/fast

#=============================================================================
# Target rules for targets named test_dataitemformatexplicit

# Build rule for target.
test_dataitemformatexplicit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dataitemformatexplicit
.PHONY : test_dataitemformatexplicit

# fast build rule for target.
test_dataitemformatexplicit/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_dataitemformatexplicit.dir/build.make tests/cpp/CMakeFiles/test_dataitemformatexplicit.dir/build
.PHONY : test_dataitemformatexplicit/fast

#=============================================================================
# Target rules for targets named test_datarecord

# Build rule for target.
test_datarecord: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_datarecord
.PHONY : test_datarecord

# fast build rule for target.
test_datarecord/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_datarecord.dir/build.make tests/cpp/CMakeFiles/test_datarecord.dir/build
.PHONY : test_datarecord/fast

#=============================================================================
# Target rules for targets named test_dataitemformatrepetitive

# Build rule for target.
test_dataitemformatrepetitive: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dataitemformatrepetitive
.PHONY : test_dataitemformatrepetitive

# fast build rule for target.
test_dataitemformatrepetitive/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_dataitemformatrepetitive.dir/build.make tests/cpp/CMakeFiles/test_dataitemformatrepetitive.dir/build
.PHONY : test_dataitemformatrepetitive/fast

#=============================================================================
# Target rules for targets named test_dataitemformatvariable

# Build rule for target.
test_dataitemformatvariable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dataitemformatvariable
.PHONY : test_dataitemformatvariable

# fast build rule for target.
test_dataitemformatvariable/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_dataitemformatvariable.dir/build.make tests/cpp/CMakeFiles/test_dataitemformatvariable.dir/build
.PHONY : test_dataitemformatvariable/fast

#=============================================================================
# Target rules for targets named test_dataitemformatbds

# Build rule for target.
test_dataitemformatbds: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dataitemformatbds
.PHONY : test_dataitemformatbds

# fast build rule for target.
test_dataitemformatbds/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_dataitemformatbds.dir/build.make tests/cpp/CMakeFiles/test_dataitemformatbds.dir/build
.PHONY : test_dataitemformatbds/fast

#=============================================================================
# Target rules for targets named test_dataitemformatcompound

# Build rule for target.
test_dataitemformatcompound: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dataitemformatcompound
.PHONY : test_dataitemformatcompound

# fast build rule for target.
test_dataitemformatcompound/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_dataitemformatcompound.dir/build.make tests/cpp/CMakeFiles/test_dataitemformatcompound.dir/build
.PHONY : test_dataitemformatcompound/fast

#=============================================================================
# Target rules for targets named test_asterixdefinition

# Build rule for target.
test_asterixdefinition: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_asterixdefinition
.PHONY : test_asterixdefinition

# fast build rule for target.
test_asterixdefinition/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_asterixdefinition.dir/build.make tests/cpp/CMakeFiles/test_asterixdefinition.dir/build
.PHONY : test_asterixdefinition/fast

#=============================================================================
# Target rules for targets named test_tracer

# Build rule for target.
test_tracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tracer
.PHONY : test_tracer

# fast build rule for target.
test_tracer/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_tracer.dir/build.make tests/cpp/CMakeFiles/test_tracer.dir/build
.PHONY : test_tracer/fast

#=============================================================================
# Target rules for targets named test_datablock

# Build rule for target.
test_datablock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_datablock
.PHONY : test_datablock

# fast build rule for target.
test_datablock/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_datablock.dir/build.make tests/cpp/CMakeFiles/test_datablock.dir/build
.PHONY : test_datablock/fast

#=============================================================================
# Target rules for targets named test_dataitemformatfixed

# Build rule for target.
test_dataitemformatfixed: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dataitemformatfixed
.PHONY : test_dataitemformatfixed

# fast build rule for target.
test_dataitemformatfixed/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_dataitemformatfixed.dir/build.make tests/cpp/CMakeFiles/test_dataitemformatfixed.dir/build
.PHONY : test_dataitemformatfixed/fast

#=============================================================================
# Target rules for targets named test_xmlparser

# Build rule for target.
test_xmlparser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_xmlparser
.PHONY : test_xmlparser

# fast build rule for target.
test_xmlparser/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_xmlparser.dir/build.make tests/cpp/CMakeFiles/test_xmlparser.dir/build
.PHONY : test_xmlparser/fast

#=============================================================================
# Target rules for targets named test_inputparser

# Build rule for target.
test_inputparser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_inputparser
.PHONY : test_inputparser

# fast build rule for target.
test_inputparser/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_inputparser.dir/build.make tests/cpp/CMakeFiles/test_inputparser.dir/build
.PHONY : test_inputparser/fast

#=============================================================================
# Target rules for targets named test_asterixdata

# Build rule for target.
test_asterixdata: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_asterixdata
.PHONY : test_asterixdata

# fast build rule for target.
test_asterixdata/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_asterixdata.dir/build.make tests/cpp/CMakeFiles/test_asterixdata.dir/build
.PHONY : test_asterixdata/fast

#=============================================================================
# Target rules for targets named test_dataitemdescription

# Build rule for target.
test_dataitemdescription: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dataitemdescription
.PHONY : test_dataitemdescription

# fast build rule for target.
test_dataitemdescription/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_dataitemdescription.dir/build.make tests/cpp/CMakeFiles/test_dataitemdescription.dir/build
.PHONY : test_dataitemdescription/fast

#=============================================================================
# Target rules for targets named test_uap

# Build rule for target.
test_uap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_uap
.PHONY : test_uap

# fast build rule for target.
test_uap/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_uap.dir/build.make tests/cpp/CMakeFiles/test_uap.dir/build
.PHONY : test_uap/fast

#=============================================================================
# Target rules for targets named test_uapitem

# Build rule for target.
test_uapitem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_uapitem
.PHONY : test_uapitem

# fast build rule for target.
test_uapitem/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_uapitem.dir/build.make tests/cpp/CMakeFiles/test_uapitem.dir/build
.PHONY : test_uapitem/fast

#=============================================================================
# Target rules for targets named test_integration_cat048

# Build rule for target.
test_integration_cat048: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_integration_cat048
.PHONY : test_integration_cat048

# fast build rule for target.
test_integration_cat048/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_integration_cat048.dir/build.make tests/cpp/CMakeFiles/test_integration_cat048.dir/build
.PHONY : test_integration_cat048/fast

#=============================================================================
# Target rules for targets named test_integration_cat062

# Build rule for target.
test_integration_cat062: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_integration_cat062
.PHONY : test_integration_cat062

# fast build rule for target.
test_integration_cat062/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_integration_cat062.dir/build.make tests/cpp/CMakeFiles/test_integration_cat062.dir/build
.PHONY : test_integration_cat062/fast

#=============================================================================
# Target rules for targets named test_integration_cat065

# Build rule for target.
test_integration_cat065: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_integration_cat065
.PHONY : test_integration_cat065

# fast build rule for target.
test_integration_cat065/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_integration_cat065.dir/build.make tests/cpp/CMakeFiles/test_integration_cat065.dir/build
.PHONY : test_integration_cat065/fast

#=============================================================================
# Target rules for targets named test_integration_error_handling

# Build rule for target.
test_integration_error_handling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_integration_error_handling
.PHONY : test_integration_error_handling

# fast build rule for target.
test_integration_error_handling/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_integration_error_handling.dir/build.make tests/cpp/CMakeFiles/test_integration_error_handling.dir/build
.PHONY : test_integration_error_handling/fast

#=============================================================================
# Target rules for targets named test_integration_pcap_format

# Build rule for target.
test_integration_pcap_format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_integration_pcap_format
.PHONY : test_integration_pcap_format

# fast build rule for target.
test_integration_pcap_format/fast:
	$(MAKE) $(MAKESILENT) -f tests/cpp/CMakeFiles/test_integration_pcap_format.dir/build.make tests/cpp/CMakeFiles/test_integration_pcap_format.dir/build
.PHONY : test_integration_pcap_format/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/asterix/AsterixData.o: src/asterix/AsterixData.cpp.o
.PHONY : src/asterix/AsterixData.o

# target to build an object file
src/asterix/AsterixData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/AsterixData.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/AsterixData.cpp.o
.PHONY : src/asterix/AsterixData.cpp.o

src/asterix/AsterixData.i: src/asterix/AsterixData.cpp.i
.PHONY : src/asterix/AsterixData.i

# target to preprocess a source file
src/asterix/AsterixData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/AsterixData.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/AsterixData.cpp.i
.PHONY : src/asterix/AsterixData.cpp.i

src/asterix/AsterixData.s: src/asterix/AsterixData.cpp.s
.PHONY : src/asterix/AsterixData.s

# target to generate assembly for a file
src/asterix/AsterixData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/AsterixData.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/AsterixData.cpp.s
.PHONY : src/asterix/AsterixData.cpp.s

src/asterix/AsterixDefinition.o: src/asterix/AsterixDefinition.cpp.o
.PHONY : src/asterix/AsterixDefinition.o

# target to build an object file
src/asterix/AsterixDefinition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/AsterixDefinition.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/AsterixDefinition.cpp.o
.PHONY : src/asterix/AsterixDefinition.cpp.o

src/asterix/AsterixDefinition.i: src/asterix/AsterixDefinition.cpp.i
.PHONY : src/asterix/AsterixDefinition.i

# target to preprocess a source file
src/asterix/AsterixDefinition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/AsterixDefinition.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/AsterixDefinition.cpp.i
.PHONY : src/asterix/AsterixDefinition.cpp.i

src/asterix/AsterixDefinition.s: src/asterix/AsterixDefinition.cpp.s
.PHONY : src/asterix/AsterixDefinition.s

# target to generate assembly for a file
src/asterix/AsterixDefinition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/AsterixDefinition.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/AsterixDefinition.cpp.s
.PHONY : src/asterix/AsterixDefinition.cpp.s

src/asterix/Category.o: src/asterix/Category.cpp.o
.PHONY : src/asterix/Category.o

# target to build an object file
src/asterix/Category.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/Category.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/Category.cpp.o
.PHONY : src/asterix/Category.cpp.o

src/asterix/Category.i: src/asterix/Category.cpp.i
.PHONY : src/asterix/Category.i

# target to preprocess a source file
src/asterix/Category.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/Category.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/Category.cpp.i
.PHONY : src/asterix/Category.cpp.i

src/asterix/Category.s: src/asterix/Category.cpp.s
.PHONY : src/asterix/Category.s

# target to generate assembly for a file
src/asterix/Category.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/Category.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/Category.cpp.s
.PHONY : src/asterix/Category.cpp.s

src/asterix/DataBlock.o: src/asterix/DataBlock.cpp.o
.PHONY : src/asterix/DataBlock.o

# target to build an object file
src/asterix/DataBlock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataBlock.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataBlock.cpp.o
.PHONY : src/asterix/DataBlock.cpp.o

src/asterix/DataBlock.i: src/asterix/DataBlock.cpp.i
.PHONY : src/asterix/DataBlock.i

# target to preprocess a source file
src/asterix/DataBlock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataBlock.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataBlock.cpp.i
.PHONY : src/asterix/DataBlock.cpp.i

src/asterix/DataBlock.s: src/asterix/DataBlock.cpp.s
.PHONY : src/asterix/DataBlock.s

# target to generate assembly for a file
src/asterix/DataBlock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataBlock.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataBlock.cpp.s
.PHONY : src/asterix/DataBlock.cpp.s

src/asterix/DataItem.o: src/asterix/DataItem.cpp.o
.PHONY : src/asterix/DataItem.o

# target to build an object file
src/asterix/DataItem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItem.cpp.o
.PHONY : src/asterix/DataItem.cpp.o

src/asterix/DataItem.i: src/asterix/DataItem.cpp.i
.PHONY : src/asterix/DataItem.i

# target to preprocess a source file
src/asterix/DataItem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItem.cpp.i
.PHONY : src/asterix/DataItem.cpp.i

src/asterix/DataItem.s: src/asterix/DataItem.cpp.s
.PHONY : src/asterix/DataItem.s

# target to generate assembly for a file
src/asterix/DataItem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItem.cpp.s
.PHONY : src/asterix/DataItem.cpp.s

src/asterix/DataItemBits.o: src/asterix/DataItemBits.cpp.o
.PHONY : src/asterix/DataItemBits.o

# target to build an object file
src/asterix/DataItemBits.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemBits.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemBits.cpp.o
.PHONY : src/asterix/DataItemBits.cpp.o

src/asterix/DataItemBits.i: src/asterix/DataItemBits.cpp.i
.PHONY : src/asterix/DataItemBits.i

# target to preprocess a source file
src/asterix/DataItemBits.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemBits.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemBits.cpp.i
.PHONY : src/asterix/DataItemBits.cpp.i

src/asterix/DataItemBits.s: src/asterix/DataItemBits.cpp.s
.PHONY : src/asterix/DataItemBits.s

# target to generate assembly for a file
src/asterix/DataItemBits.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemBits.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemBits.cpp.s
.PHONY : src/asterix/DataItemBits.cpp.s

src/asterix/DataItemDescription.o: src/asterix/DataItemDescription.cpp.o
.PHONY : src/asterix/DataItemDescription.o

# target to build an object file
src/asterix/DataItemDescription.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemDescription.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemDescription.cpp.o
.PHONY : src/asterix/DataItemDescription.cpp.o

src/asterix/DataItemDescription.i: src/asterix/DataItemDescription.cpp.i
.PHONY : src/asterix/DataItemDescription.i

# target to preprocess a source file
src/asterix/DataItemDescription.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemDescription.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemDescription.cpp.i
.PHONY : src/asterix/DataItemDescription.cpp.i

src/asterix/DataItemDescription.s: src/asterix/DataItemDescription.cpp.s
.PHONY : src/asterix/DataItemDescription.s

# target to generate assembly for a file
src/asterix/DataItemDescription.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemDescription.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemDescription.cpp.s
.PHONY : src/asterix/DataItemDescription.cpp.s

src/asterix/DataItemFormat.o: src/asterix/DataItemFormat.cpp.o
.PHONY : src/asterix/DataItemFormat.o

# target to build an object file
src/asterix/DataItemFormat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormat.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormat.cpp.o
.PHONY : src/asterix/DataItemFormat.cpp.o

src/asterix/DataItemFormat.i: src/asterix/DataItemFormat.cpp.i
.PHONY : src/asterix/DataItemFormat.i

# target to preprocess a source file
src/asterix/DataItemFormat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormat.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormat.cpp.i
.PHONY : src/asterix/DataItemFormat.cpp.i

src/asterix/DataItemFormat.s: src/asterix/DataItemFormat.cpp.s
.PHONY : src/asterix/DataItemFormat.s

# target to generate assembly for a file
src/asterix/DataItemFormat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormat.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormat.cpp.s
.PHONY : src/asterix/DataItemFormat.cpp.s

src/asterix/DataItemFormatBDS.o: src/asterix/DataItemFormatBDS.cpp.o
.PHONY : src/asterix/DataItemFormatBDS.o

# target to build an object file
src/asterix/DataItemFormatBDS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatBDS.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatBDS.cpp.o
.PHONY : src/asterix/DataItemFormatBDS.cpp.o

src/asterix/DataItemFormatBDS.i: src/asterix/DataItemFormatBDS.cpp.i
.PHONY : src/asterix/DataItemFormatBDS.i

# target to preprocess a source file
src/asterix/DataItemFormatBDS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatBDS.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatBDS.cpp.i
.PHONY : src/asterix/DataItemFormatBDS.cpp.i

src/asterix/DataItemFormatBDS.s: src/asterix/DataItemFormatBDS.cpp.s
.PHONY : src/asterix/DataItemFormatBDS.s

# target to generate assembly for a file
src/asterix/DataItemFormatBDS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatBDS.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatBDS.cpp.s
.PHONY : src/asterix/DataItemFormatBDS.cpp.s

src/asterix/DataItemFormatCompound.o: src/asterix/DataItemFormatCompound.cpp.o
.PHONY : src/asterix/DataItemFormatCompound.o

# target to build an object file
src/asterix/DataItemFormatCompound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatCompound.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatCompound.cpp.o
.PHONY : src/asterix/DataItemFormatCompound.cpp.o

src/asterix/DataItemFormatCompound.i: src/asterix/DataItemFormatCompound.cpp.i
.PHONY : src/asterix/DataItemFormatCompound.i

# target to preprocess a source file
src/asterix/DataItemFormatCompound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatCompound.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatCompound.cpp.i
.PHONY : src/asterix/DataItemFormatCompound.cpp.i

src/asterix/DataItemFormatCompound.s: src/asterix/DataItemFormatCompound.cpp.s
.PHONY : src/asterix/DataItemFormatCompound.s

# target to generate assembly for a file
src/asterix/DataItemFormatCompound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatCompound.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatCompound.cpp.s
.PHONY : src/asterix/DataItemFormatCompound.cpp.s

src/asterix/DataItemFormatExplicit.o: src/asterix/DataItemFormatExplicit.cpp.o
.PHONY : src/asterix/DataItemFormatExplicit.o

# target to build an object file
src/asterix/DataItemFormatExplicit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatExplicit.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatExplicit.cpp.o
.PHONY : src/asterix/DataItemFormatExplicit.cpp.o

src/asterix/DataItemFormatExplicit.i: src/asterix/DataItemFormatExplicit.cpp.i
.PHONY : src/asterix/DataItemFormatExplicit.i

# target to preprocess a source file
src/asterix/DataItemFormatExplicit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatExplicit.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatExplicit.cpp.i
.PHONY : src/asterix/DataItemFormatExplicit.cpp.i

src/asterix/DataItemFormatExplicit.s: src/asterix/DataItemFormatExplicit.cpp.s
.PHONY : src/asterix/DataItemFormatExplicit.s

# target to generate assembly for a file
src/asterix/DataItemFormatExplicit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatExplicit.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatExplicit.cpp.s
.PHONY : src/asterix/DataItemFormatExplicit.cpp.s

src/asterix/DataItemFormatFixed.o: src/asterix/DataItemFormatFixed.cpp.o
.PHONY : src/asterix/DataItemFormatFixed.o

# target to build an object file
src/asterix/DataItemFormatFixed.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatFixed.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatFixed.cpp.o
.PHONY : src/asterix/DataItemFormatFixed.cpp.o

src/asterix/DataItemFormatFixed.i: src/asterix/DataItemFormatFixed.cpp.i
.PHONY : src/asterix/DataItemFormatFixed.i

# target to preprocess a source file
src/asterix/DataItemFormatFixed.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatFixed.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatFixed.cpp.i
.PHONY : src/asterix/DataItemFormatFixed.cpp.i

src/asterix/DataItemFormatFixed.s: src/asterix/DataItemFormatFixed.cpp.s
.PHONY : src/asterix/DataItemFormatFixed.s

# target to generate assembly for a file
src/asterix/DataItemFormatFixed.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatFixed.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatFixed.cpp.s
.PHONY : src/asterix/DataItemFormatFixed.cpp.s

src/asterix/DataItemFormatRepetitive.o: src/asterix/DataItemFormatRepetitive.cpp.o
.PHONY : src/asterix/DataItemFormatRepetitive.o

# target to build an object file
src/asterix/DataItemFormatRepetitive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatRepetitive.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatRepetitive.cpp.o
.PHONY : src/asterix/DataItemFormatRepetitive.cpp.o

src/asterix/DataItemFormatRepetitive.i: src/asterix/DataItemFormatRepetitive.cpp.i
.PHONY : src/asterix/DataItemFormatRepetitive.i

# target to preprocess a source file
src/asterix/DataItemFormatRepetitive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatRepetitive.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatRepetitive.cpp.i
.PHONY : src/asterix/DataItemFormatRepetitive.cpp.i

src/asterix/DataItemFormatRepetitive.s: src/asterix/DataItemFormatRepetitive.cpp.s
.PHONY : src/asterix/DataItemFormatRepetitive.s

# target to generate assembly for a file
src/asterix/DataItemFormatRepetitive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatRepetitive.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatRepetitive.cpp.s
.PHONY : src/asterix/DataItemFormatRepetitive.cpp.s

src/asterix/DataItemFormatVariable.o: src/asterix/DataItemFormatVariable.cpp.o
.PHONY : src/asterix/DataItemFormatVariable.o

# target to build an object file
src/asterix/DataItemFormatVariable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatVariable.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatVariable.cpp.o
.PHONY : src/asterix/DataItemFormatVariable.cpp.o

src/asterix/DataItemFormatVariable.i: src/asterix/DataItemFormatVariable.cpp.i
.PHONY : src/asterix/DataItemFormatVariable.i

# target to preprocess a source file
src/asterix/DataItemFormatVariable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatVariable.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatVariable.cpp.i
.PHONY : src/asterix/DataItemFormatVariable.cpp.i

src/asterix/DataItemFormatVariable.s: src/asterix/DataItemFormatVariable.cpp.s
.PHONY : src/asterix/DataItemFormatVariable.s

# target to generate assembly for a file
src/asterix/DataItemFormatVariable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataItemFormatVariable.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataItemFormatVariable.cpp.s
.PHONY : src/asterix/DataItemFormatVariable.cpp.s

src/asterix/DataRecord.o: src/asterix/DataRecord.cpp.o
.PHONY : src/asterix/DataRecord.o

# target to build an object file
src/asterix/DataRecord.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataRecord.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataRecord.cpp.o
.PHONY : src/asterix/DataRecord.cpp.o

src/asterix/DataRecord.i: src/asterix/DataRecord.cpp.i
.PHONY : src/asterix/DataRecord.i

# target to preprocess a source file
src/asterix/DataRecord.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataRecord.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataRecord.cpp.i
.PHONY : src/asterix/DataRecord.cpp.i

src/asterix/DataRecord.s: src/asterix/DataRecord.cpp.s
.PHONY : src/asterix/DataRecord.s

# target to generate assembly for a file
src/asterix/DataRecord.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/DataRecord.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/DataRecord.cpp.s
.PHONY : src/asterix/DataRecord.cpp.s

src/asterix/InputParser.o: src/asterix/InputParser.cpp.o
.PHONY : src/asterix/InputParser.o

# target to build an object file
src/asterix/InputParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/InputParser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/InputParser.cpp.o
.PHONY : src/asterix/InputParser.cpp.o

src/asterix/InputParser.i: src/asterix/InputParser.cpp.i
.PHONY : src/asterix/InputParser.i

# target to preprocess a source file
src/asterix/InputParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/InputParser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/InputParser.cpp.i
.PHONY : src/asterix/InputParser.cpp.i

src/asterix/InputParser.s: src/asterix/InputParser.cpp.s
.PHONY : src/asterix/InputParser.s

# target to generate assembly for a file
src/asterix/InputParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/InputParser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/InputParser.cpp.s
.PHONY : src/asterix/InputParser.cpp.s

src/asterix/Tracer.o: src/asterix/Tracer.cpp.o
.PHONY : src/asterix/Tracer.o

# target to build an object file
src/asterix/Tracer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/Tracer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/Tracer.cpp.o
.PHONY : src/asterix/Tracer.cpp.o

src/asterix/Tracer.i: src/asterix/Tracer.cpp.i
.PHONY : src/asterix/Tracer.i

# target to preprocess a source file
src/asterix/Tracer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/Tracer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/Tracer.cpp.i
.PHONY : src/asterix/Tracer.cpp.i

src/asterix/Tracer.s: src/asterix/Tracer.cpp.s
.PHONY : src/asterix/Tracer.s

# target to generate assembly for a file
src/asterix/Tracer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/Tracer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/Tracer.cpp.s
.PHONY : src/asterix/Tracer.cpp.s

src/asterix/UAP.o: src/asterix/UAP.cpp.o
.PHONY : src/asterix/UAP.o

# target to build an object file
src/asterix/UAP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/UAP.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/UAP.cpp.o
.PHONY : src/asterix/UAP.cpp.o

src/asterix/UAP.i: src/asterix/UAP.cpp.i
.PHONY : src/asterix/UAP.i

# target to preprocess a source file
src/asterix/UAP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/UAP.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/UAP.cpp.i
.PHONY : src/asterix/UAP.cpp.i

src/asterix/UAP.s: src/asterix/UAP.cpp.s
.PHONY : src/asterix/UAP.s

# target to generate assembly for a file
src/asterix/UAP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/UAP.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/UAP.cpp.s
.PHONY : src/asterix/UAP.cpp.s

src/asterix/UAPItem.o: src/asterix/UAPItem.cpp.o
.PHONY : src/asterix/UAPItem.o

# target to build an object file
src/asterix/UAPItem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/UAPItem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/UAPItem.cpp.o
.PHONY : src/asterix/UAPItem.cpp.o

src/asterix/UAPItem.i: src/asterix/UAPItem.cpp.i
.PHONY : src/asterix/UAPItem.i

# target to preprocess a source file
src/asterix/UAPItem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/UAPItem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/UAPItem.cpp.i
.PHONY : src/asterix/UAPItem.cpp.i

src/asterix/UAPItem.s: src/asterix/UAPItem.cpp.s
.PHONY : src/asterix/UAPItem.s

# target to generate assembly for a file
src/asterix/UAPItem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/UAPItem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/UAPItem.cpp.s
.PHONY : src/asterix/UAPItem.cpp.s

src/asterix/Utils.o: src/asterix/Utils.cpp.o
.PHONY : src/asterix/Utils.o

# target to build an object file
src/asterix/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/Utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/Utils.cpp.o
.PHONY : src/asterix/Utils.cpp.o

src/asterix/Utils.i: src/asterix/Utils.cpp.i
.PHONY : src/asterix/Utils.i

# target to preprocess a source file
src/asterix/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/Utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/Utils.cpp.i
.PHONY : src/asterix/Utils.cpp.i

src/asterix/Utils.s: src/asterix/Utils.cpp.s
.PHONY : src/asterix/Utils.s

# target to generate assembly for a file
src/asterix/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/Utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/Utils.cpp.s
.PHONY : src/asterix/Utils.cpp.s

src/asterix/XMLParser.o: src/asterix/XMLParser.cpp.o
.PHONY : src/asterix/XMLParser.o

# target to build an object file
src/asterix/XMLParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/XMLParser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/XMLParser.cpp.o
.PHONY : src/asterix/XMLParser.cpp.o

src/asterix/XMLParser.i: src/asterix/XMLParser.cpp.i
.PHONY : src/asterix/XMLParser.i

# target to preprocess a source file
src/asterix/XMLParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/XMLParser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/XMLParser.cpp.i
.PHONY : src/asterix/XMLParser.cpp.i

src/asterix/XMLParser.s: src/asterix/XMLParser.cpp.s
.PHONY : src/asterix/XMLParser.s

# target to generate assembly for a file
src/asterix/XMLParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/XMLParser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/XMLParser.cpp.s
.PHONY : src/asterix/XMLParser.cpp.s

src/asterix/asterixfinalsubformat.o: src/asterix/asterixfinalsubformat.cxx.o
.PHONY : src/asterix/asterixfinalsubformat.o

# target to build an object file
src/asterix/asterixfinalsubformat.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixfinalsubformat.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixfinalsubformat.cxx.o
.PHONY : src/asterix/asterixfinalsubformat.cxx.o

src/asterix/asterixfinalsubformat.i: src/asterix/asterixfinalsubformat.cxx.i
.PHONY : src/asterix/asterixfinalsubformat.i

# target to preprocess a source file
src/asterix/asterixfinalsubformat.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixfinalsubformat.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixfinalsubformat.cxx.i
.PHONY : src/asterix/asterixfinalsubformat.cxx.i

src/asterix/asterixfinalsubformat.s: src/asterix/asterixfinalsubformat.cxx.s
.PHONY : src/asterix/asterixfinalsubformat.s

# target to generate assembly for a file
src/asterix/asterixfinalsubformat.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixfinalsubformat.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixfinalsubformat.cxx.s
.PHONY : src/asterix/asterixfinalsubformat.cxx.s

src/asterix/asterixformat.o: src/asterix/asterixformat.cxx.o
.PHONY : src/asterix/asterixformat.o

# target to build an object file
src/asterix/asterixformat.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixformat.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixformat.cxx.o
.PHONY : src/asterix/asterixformat.cxx.o

src/asterix/asterixformat.i: src/asterix/asterixformat.cxx.i
.PHONY : src/asterix/asterixformat.i

# target to preprocess a source file
src/asterix/asterixformat.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixformat.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixformat.cxx.i
.PHONY : src/asterix/asterixformat.cxx.i

src/asterix/asterixformat.s: src/asterix/asterixformat.cxx.s
.PHONY : src/asterix/asterixformat.s

# target to generate assembly for a file
src/asterix/asterixformat.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixformat.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixformat.cxx.s
.PHONY : src/asterix/asterixformat.cxx.s

src/asterix/asterixgpssubformat.o: src/asterix/asterixgpssubformat.cxx.o
.PHONY : src/asterix/asterixgpssubformat.o

# target to build an object file
src/asterix/asterixgpssubformat.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixgpssubformat.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixgpssubformat.cxx.o
.PHONY : src/asterix/asterixgpssubformat.cxx.o

src/asterix/asterixgpssubformat.i: src/asterix/asterixgpssubformat.cxx.i
.PHONY : src/asterix/asterixgpssubformat.i

# target to preprocess a source file
src/asterix/asterixgpssubformat.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixgpssubformat.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixgpssubformat.cxx.i
.PHONY : src/asterix/asterixgpssubformat.cxx.i

src/asterix/asterixgpssubformat.s: src/asterix/asterixgpssubformat.cxx.s
.PHONY : src/asterix/asterixgpssubformat.s

# target to generate assembly for a file
src/asterix/asterixgpssubformat.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixgpssubformat.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixgpssubformat.cxx.s
.PHONY : src/asterix/asterixgpssubformat.cxx.s

src/asterix/asterixhdlcparsing.o: src/asterix/asterixhdlcparsing.c.o
.PHONY : src/asterix/asterixhdlcparsing.o

# target to build an object file
src/asterix/asterixhdlcparsing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixhdlcparsing.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixhdlcparsing.c.o
.PHONY : src/asterix/asterixhdlcparsing.c.o

src/asterix/asterixhdlcparsing.i: src/asterix/asterixhdlcparsing.c.i
.PHONY : src/asterix/asterixhdlcparsing.i

# target to preprocess a source file
src/asterix/asterixhdlcparsing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixhdlcparsing.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixhdlcparsing.c.i
.PHONY : src/asterix/asterixhdlcparsing.c.i

src/asterix/asterixhdlcparsing.s: src/asterix/asterixhdlcparsing.c.s
.PHONY : src/asterix/asterixhdlcparsing.s

# target to generate assembly for a file
src/asterix/asterixhdlcparsing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixhdlcparsing.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixhdlcparsing.c.s
.PHONY : src/asterix/asterixhdlcparsing.c.s

src/asterix/asterixhdlcsubformat.o: src/asterix/asterixhdlcsubformat.cxx.o
.PHONY : src/asterix/asterixhdlcsubformat.o

# target to build an object file
src/asterix/asterixhdlcsubformat.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixhdlcsubformat.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixhdlcsubformat.cxx.o
.PHONY : src/asterix/asterixhdlcsubformat.cxx.o

src/asterix/asterixhdlcsubformat.i: src/asterix/asterixhdlcsubformat.cxx.i
.PHONY : src/asterix/asterixhdlcsubformat.i

# target to preprocess a source file
src/asterix/asterixhdlcsubformat.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixhdlcsubformat.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixhdlcsubformat.cxx.i
.PHONY : src/asterix/asterixhdlcsubformat.cxx.i

src/asterix/asterixhdlcsubformat.s: src/asterix/asterixhdlcsubformat.cxx.s
.PHONY : src/asterix/asterixhdlcsubformat.s

# target to generate assembly for a file
src/asterix/asterixhdlcsubformat.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixhdlcsubformat.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixhdlcsubformat.cxx.s
.PHONY : src/asterix/asterixhdlcsubformat.cxx.s

src/asterix/asterixpcapsubformat.o: src/asterix/asterixpcapsubformat.cxx.o
.PHONY : src/asterix/asterixpcapsubformat.o

# target to build an object file
src/asterix/asterixpcapsubformat.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixpcapsubformat.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixpcapsubformat.cxx.o
.PHONY : src/asterix/asterixpcapsubformat.cxx.o

src/asterix/asterixpcapsubformat.i: src/asterix/asterixpcapsubformat.cxx.i
.PHONY : src/asterix/asterixpcapsubformat.i

# target to preprocess a source file
src/asterix/asterixpcapsubformat.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixpcapsubformat.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixpcapsubformat.cxx.i
.PHONY : src/asterix/asterixpcapsubformat.cxx.i

src/asterix/asterixpcapsubformat.s: src/asterix/asterixpcapsubformat.cxx.s
.PHONY : src/asterix/asterixpcapsubformat.s

# target to generate assembly for a file
src/asterix/asterixpcapsubformat.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixpcapsubformat.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixpcapsubformat.cxx.s
.PHONY : src/asterix/asterixpcapsubformat.cxx.s

src/asterix/asterixrawsubformat.o: src/asterix/asterixrawsubformat.cxx.o
.PHONY : src/asterix/asterixrawsubformat.o

# target to build an object file
src/asterix/asterixrawsubformat.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixrawsubformat.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixrawsubformat.cxx.o
.PHONY : src/asterix/asterixrawsubformat.cxx.o

src/asterix/asterixrawsubformat.i: src/asterix/asterixrawsubformat.cxx.i
.PHONY : src/asterix/asterixrawsubformat.i

# target to preprocess a source file
src/asterix/asterixrawsubformat.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixrawsubformat.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixrawsubformat.cxx.i
.PHONY : src/asterix/asterixrawsubformat.cxx.i

src/asterix/asterixrawsubformat.s: src/asterix/asterixrawsubformat.cxx.s
.PHONY : src/asterix/asterixrawsubformat.s

# target to generate assembly for a file
src/asterix/asterixrawsubformat.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/asterix/asterixrawsubformat.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/asterix/asterixrawsubformat.cxx.s
.PHONY : src/asterix/asterixrawsubformat.cxx.s

src/engine/channelfactory.o: src/engine/channelfactory.cxx.o
.PHONY : src/engine/channelfactory.o

# target to build an object file
src/engine/channelfactory.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/channelfactory.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/channelfactory.cxx.o
.PHONY : src/engine/channelfactory.cxx.o

src/engine/channelfactory.i: src/engine/channelfactory.cxx.i
.PHONY : src/engine/channelfactory.i

# target to preprocess a source file
src/engine/channelfactory.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/channelfactory.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/channelfactory.cxx.i
.PHONY : src/engine/channelfactory.cxx.i

src/engine/channelfactory.s: src/engine/channelfactory.cxx.s
.PHONY : src/engine/channelfactory.s

# target to generate assembly for a file
src/engine/channelfactory.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/channelfactory.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/channelfactory.cxx.s
.PHONY : src/engine/channelfactory.cxx.s

src/engine/converterengine.o: src/engine/converterengine.cxx.o
.PHONY : src/engine/converterengine.o

# target to build an object file
src/engine/converterengine.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/converterengine.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/converterengine.cxx.o
.PHONY : src/engine/converterengine.cxx.o

src/engine/converterengine.i: src/engine/converterengine.cxx.i
.PHONY : src/engine/converterengine.i

# target to preprocess a source file
src/engine/converterengine.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/converterengine.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/converterengine.cxx.i
.PHONY : src/engine/converterengine.cxx.i

src/engine/converterengine.s: src/engine/converterengine.cxx.s
.PHONY : src/engine/converterengine.s

# target to generate assembly for a file
src/engine/converterengine.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/converterengine.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/converterengine.cxx.s
.PHONY : src/engine/converterengine.cxx.s

src/engine/descriptor.o: src/engine/descriptor.cxx.o
.PHONY : src/engine/descriptor.o

# target to build an object file
src/engine/descriptor.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/descriptor.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/descriptor.cxx.o
.PHONY : src/engine/descriptor.cxx.o

src/engine/descriptor.i: src/engine/descriptor.cxx.i
.PHONY : src/engine/descriptor.i

# target to preprocess a source file
src/engine/descriptor.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/descriptor.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/descriptor.cxx.i
.PHONY : src/engine/descriptor.cxx.i

src/engine/descriptor.s: src/engine/descriptor.cxx.s
.PHONY : src/engine/descriptor.s

# target to generate assembly for a file
src/engine/descriptor.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/descriptor.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/descriptor.cxx.s
.PHONY : src/engine/descriptor.cxx.s

src/engine/devicefactory.o: src/engine/devicefactory.cxx.o
.PHONY : src/engine/devicefactory.o

# target to build an object file
src/engine/devicefactory.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/devicefactory.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/devicefactory.cxx.o
.PHONY : src/engine/devicefactory.cxx.o

src/engine/devicefactory.i: src/engine/devicefactory.cxx.i
.PHONY : src/engine/devicefactory.i

# target to preprocess a source file
src/engine/devicefactory.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/devicefactory.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/devicefactory.cxx.i
.PHONY : src/engine/devicefactory.cxx.i

src/engine/devicefactory.s: src/engine/devicefactory.cxx.s
.PHONY : src/engine/devicefactory.s

# target to generate assembly for a file
src/engine/devicefactory.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/devicefactory.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/devicefactory.cxx.s
.PHONY : src/engine/devicefactory.cxx.s

src/engine/diskdevice.o: src/engine/diskdevice.cxx.o
.PHONY : src/engine/diskdevice.o

# target to build an object file
src/engine/diskdevice.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/diskdevice.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/diskdevice.cxx.o
.PHONY : src/engine/diskdevice.cxx.o

src/engine/diskdevice.i: src/engine/diskdevice.cxx.i
.PHONY : src/engine/diskdevice.i

# target to preprocess a source file
src/engine/diskdevice.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/diskdevice.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/diskdevice.cxx.i
.PHONY : src/engine/diskdevice.cxx.i

src/engine/diskdevice.s: src/engine/diskdevice.cxx.s
.PHONY : src/engine/diskdevice.s

# target to generate assembly for a file
src/engine/diskdevice.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/diskdevice.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/diskdevice.cxx.s
.PHONY : src/engine/diskdevice.cxx.s

src/engine/serialdevice.o: src/engine/serialdevice.cxx.o
.PHONY : src/engine/serialdevice.o

# target to build an object file
src/engine/serialdevice.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/serialdevice.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/serialdevice.cxx.o
.PHONY : src/engine/serialdevice.cxx.o

src/engine/serialdevice.i: src/engine/serialdevice.cxx.i
.PHONY : src/engine/serialdevice.i

# target to preprocess a source file
src/engine/serialdevice.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/serialdevice.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/serialdevice.cxx.i
.PHONY : src/engine/serialdevice.cxx.i

src/engine/serialdevice.s: src/engine/serialdevice.cxx.s
.PHONY : src/engine/serialdevice.s

# target to generate assembly for a file
src/engine/serialdevice.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/serialdevice.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/serialdevice.cxx.s
.PHONY : src/engine/serialdevice.cxx.s

src/engine/stddevice.o: src/engine/stddevice.cxx.o
.PHONY : src/engine/stddevice.o

# target to build an object file
src/engine/stddevice.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/stddevice.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/stddevice.cxx.o
.PHONY : src/engine/stddevice.cxx.o

src/engine/stddevice.i: src/engine/stddevice.cxx.i
.PHONY : src/engine/stddevice.i

# target to preprocess a source file
src/engine/stddevice.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/stddevice.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/stddevice.cxx.i
.PHONY : src/engine/stddevice.cxx.i

src/engine/stddevice.s: src/engine/stddevice.cxx.s
.PHONY : src/engine/stddevice.s

# target to generate assembly for a file
src/engine/stddevice.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/stddevice.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/stddevice.cxx.s
.PHONY : src/engine/stddevice.cxx.s

src/engine/tcpdevice.o: src/engine/tcpdevice.cxx.o
.PHONY : src/engine/tcpdevice.o

# target to build an object file
src/engine/tcpdevice.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/tcpdevice.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/tcpdevice.cxx.o
.PHONY : src/engine/tcpdevice.cxx.o

src/engine/tcpdevice.i: src/engine/tcpdevice.cxx.i
.PHONY : src/engine/tcpdevice.i

# target to preprocess a source file
src/engine/tcpdevice.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/tcpdevice.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/tcpdevice.cxx.i
.PHONY : src/engine/tcpdevice.cxx.i

src/engine/tcpdevice.s: src/engine/tcpdevice.cxx.s
.PHONY : src/engine/tcpdevice.s

# target to generate assembly for a file
src/engine/tcpdevice.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/tcpdevice.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/tcpdevice.cxx.s
.PHONY : src/engine/tcpdevice.cxx.s

src/engine/udpdevice.o: src/engine/udpdevice.cxx.o
.PHONY : src/engine/udpdevice.o

# target to build an object file
src/engine/udpdevice.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/udpdevice.cxx.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/udpdevice.cxx.o
.PHONY : src/engine/udpdevice.cxx.o

src/engine/udpdevice.i: src/engine/udpdevice.cxx.i
.PHONY : src/engine/udpdevice.i

# target to preprocess a source file
src/engine/udpdevice.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/udpdevice.cxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/udpdevice.cxx.i
.PHONY : src/engine/udpdevice.cxx.i

src/engine/udpdevice.s: src/engine/udpdevice.cxx.s
.PHONY : src/engine/udpdevice.s

# target to generate assembly for a file
src/engine/udpdevice.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_shared.dir/build.make CMakeFiles/asterix_shared.dir/src/engine/udpdevice.cxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_static.dir/build.make CMakeFiles/asterix_static.dir/src/engine/udpdevice.cxx.s
.PHONY : src/engine/udpdevice.cxx.s

src/main/asterix.o: src/main/asterix.cpp.o
.PHONY : src/main/asterix.o

# target to build an object file
src/main/asterix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_exe.dir/build.make CMakeFiles/asterix_exe.dir/src/main/asterix.cpp.o
.PHONY : src/main/asterix.cpp.o

src/main/asterix.i: src/main/asterix.cpp.i
.PHONY : src/main/asterix.i

# target to preprocess a source file
src/main/asterix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_exe.dir/build.make CMakeFiles/asterix_exe.dir/src/main/asterix.cpp.i
.PHONY : src/main/asterix.cpp.i

src/main/asterix.s: src/main/asterix.cpp.s
.PHONY : src/main/asterix.s

# target to generate assembly for a file
src/main/asterix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asterix_exe.dir/build.make CMakeFiles/asterix_exe.dir/src/main/asterix.cpp.s
.PHONY : src/main/asterix.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... asterix_exe"
	@echo "... asterix_shared"
	@echo "... asterix_static"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... test_asterixdata"
	@echo "... test_asterixdefinition"
	@echo "... test_category"
	@echo "... test_datablock"
	@echo "... test_dataitem"
	@echo "... test_dataitembits"
	@echo "... test_dataitemdescription"
	@echo "... test_dataitemformatbds"
	@echo "... test_dataitemformatcompound"
	@echo "... test_dataitemformatexplicit"
	@echo "... test_dataitemformatfixed"
	@echo "... test_dataitemformatrepetitive"
	@echo "... test_dataitemformatvariable"
	@echo "... test_datarecord"
	@echo "... test_inputparser"
	@echo "... test_integration_cat048"
	@echo "... test_integration_cat062"
	@echo "... test_integration_cat065"
	@echo "... test_integration_error_handling"
	@echo "... test_integration_pcap_format"
	@echo "... test_tracer"
	@echo "... test_uap"
	@echo "... test_uapitem"
	@echo "... test_utils"
	@echo "... test_xmlparser"
	@echo "... src/asterix/AsterixData.o"
	@echo "... src/asterix/AsterixData.i"
	@echo "... src/asterix/AsterixData.s"
	@echo "... src/asterix/AsterixDefinition.o"
	@echo "... src/asterix/AsterixDefinition.i"
	@echo "... src/asterix/AsterixDefinition.s"
	@echo "... src/asterix/Category.o"
	@echo "... src/asterix/Category.i"
	@echo "... src/asterix/Category.s"
	@echo "... src/asterix/DataBlock.o"
	@echo "... src/asterix/DataBlock.i"
	@echo "... src/asterix/DataBlock.s"
	@echo "... src/asterix/DataItem.o"
	@echo "... src/asterix/DataItem.i"
	@echo "... src/asterix/DataItem.s"
	@echo "... src/asterix/DataItemBits.o"
	@echo "... src/asterix/DataItemBits.i"
	@echo "... src/asterix/DataItemBits.s"
	@echo "... src/asterix/DataItemDescription.o"
	@echo "... src/asterix/DataItemDescription.i"
	@echo "... src/asterix/DataItemDescription.s"
	@echo "... src/asterix/DataItemFormat.o"
	@echo "... src/asterix/DataItemFormat.i"
	@echo "... src/asterix/DataItemFormat.s"
	@echo "... src/asterix/DataItemFormatBDS.o"
	@echo "... src/asterix/DataItemFormatBDS.i"
	@echo "... src/asterix/DataItemFormatBDS.s"
	@echo "... src/asterix/DataItemFormatCompound.o"
	@echo "... src/asterix/DataItemFormatCompound.i"
	@echo "... src/asterix/DataItemFormatCompound.s"
	@echo "... src/asterix/DataItemFormatExplicit.o"
	@echo "... src/asterix/DataItemFormatExplicit.i"
	@echo "... src/asterix/DataItemFormatExplicit.s"
	@echo "... src/asterix/DataItemFormatFixed.o"
	@echo "... src/asterix/DataItemFormatFixed.i"
	@echo "... src/asterix/DataItemFormatFixed.s"
	@echo "... src/asterix/DataItemFormatRepetitive.o"
	@echo "... src/asterix/DataItemFormatRepetitive.i"
	@echo "... src/asterix/DataItemFormatRepetitive.s"
	@echo "... src/asterix/DataItemFormatVariable.o"
	@echo "... src/asterix/DataItemFormatVariable.i"
	@echo "... src/asterix/DataItemFormatVariable.s"
	@echo "... src/asterix/DataRecord.o"
	@echo "... src/asterix/DataRecord.i"
	@echo "... src/asterix/DataRecord.s"
	@echo "... src/asterix/InputParser.o"
	@echo "... src/asterix/InputParser.i"
	@echo "... src/asterix/InputParser.s"
	@echo "... src/asterix/Tracer.o"
	@echo "... src/asterix/Tracer.i"
	@echo "... src/asterix/Tracer.s"
	@echo "... src/asterix/UAP.o"
	@echo "... src/asterix/UAP.i"
	@echo "... src/asterix/UAP.s"
	@echo "... src/asterix/UAPItem.o"
	@echo "... src/asterix/UAPItem.i"
	@echo "... src/asterix/UAPItem.s"
	@echo "... src/asterix/Utils.o"
	@echo "... src/asterix/Utils.i"
	@echo "... src/asterix/Utils.s"
	@echo "... src/asterix/XMLParser.o"
	@echo "... src/asterix/XMLParser.i"
	@echo "... src/asterix/XMLParser.s"
	@echo "... src/asterix/asterixfinalsubformat.o"
	@echo "... src/asterix/asterixfinalsubformat.i"
	@echo "... src/asterix/asterixfinalsubformat.s"
	@echo "... src/asterix/asterixformat.o"
	@echo "... src/asterix/asterixformat.i"
	@echo "... src/asterix/asterixformat.s"
	@echo "... src/asterix/asterixgpssubformat.o"
	@echo "... src/asterix/asterixgpssubformat.i"
	@echo "... src/asterix/asterixgpssubformat.s"
	@echo "... src/asterix/asterixhdlcparsing.o"
	@echo "... src/asterix/asterixhdlcparsing.i"
	@echo "... src/asterix/asterixhdlcparsing.s"
	@echo "... src/asterix/asterixhdlcsubformat.o"
	@echo "... src/asterix/asterixhdlcsubformat.i"
	@echo "... src/asterix/asterixhdlcsubformat.s"
	@echo "... src/asterix/asterixpcapsubformat.o"
	@echo "... src/asterix/asterixpcapsubformat.i"
	@echo "... src/asterix/asterixpcapsubformat.s"
	@echo "... src/asterix/asterixrawsubformat.o"
	@echo "... src/asterix/asterixrawsubformat.i"
	@echo "... src/asterix/asterixrawsubformat.s"
	@echo "... src/engine/channelfactory.o"
	@echo "... src/engine/channelfactory.i"
	@echo "... src/engine/channelfactory.s"
	@echo "... src/engine/converterengine.o"
	@echo "... src/engine/converterengine.i"
	@echo "... src/engine/converterengine.s"
	@echo "... src/engine/descriptor.o"
	@echo "... src/engine/descriptor.i"
	@echo "... src/engine/descriptor.s"
	@echo "... src/engine/devicefactory.o"
	@echo "... src/engine/devicefactory.i"
	@echo "... src/engine/devicefactory.s"
	@echo "... src/engine/diskdevice.o"
	@echo "... src/engine/diskdevice.i"
	@echo "... src/engine/diskdevice.s"
	@echo "... src/engine/serialdevice.o"
	@echo "... src/engine/serialdevice.i"
	@echo "... src/engine/serialdevice.s"
	@echo "... src/engine/stddevice.o"
	@echo "... src/engine/stddevice.i"
	@echo "... src/engine/stddevice.s"
	@echo "... src/engine/tcpdevice.o"
	@echo "... src/engine/tcpdevice.i"
	@echo "... src/engine/tcpdevice.s"
	@echo "... src/engine/udpdevice.o"
	@echo "... src/engine/udpdevice.i"
	@echo "... src/engine/udpdevice.s"
	@echo "... src/main/asterix.o"
	@echo "... src/main/asterix.i"
	@echo "... src/main/asterix.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

