if(EXISTS "/home/e/Development/asterix/tests/cpp/test_dataitemformatvariable[1]_tests.cmake")
  include("/home/e/Development/asterix/tests/cpp/test_dataitemformatvariable[1]_tests.cmake")
else()
  add_test(test_dataitemformatvariable_NOT_BUILT test_dataitemformatvariable_NOT_BUILT)
endif()
