if(EXISTS "/home/e/Development/asterix/tests/cpp/test_inputparser[1]_tests.cmake")
  include("/home/e/Development/asterix/tests/cpp/test_inputparser[1]_tests.cmake")
else()
  add_test(test_inputparser_NOT_BUILT test_inputparser_NOT_BUILT)
endif()
