add_test([=[DataItemTest.ConstructorInitializes]=]  /path/to/asterix/bin/test_dataitem [==[--gtest_filter=DataItemTest.ConstructorInitializes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataItemTest.ConstructorInitializes]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataItemTest.InitialLengthIsZero]=]  /path/to/asterix/bin/test_dataitem [==[--gtest_filter=DataItemTest.InitialLengthIsZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataItemTest.InitialLengthIsZero]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataItemTest.NullDescriptionHandled]=]  /path/to/asterix/bin/test_dataitem [==[--gtest_filter=DataItemTest.NullDescriptionHandled]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataItemTest.NullDescriptionHandled]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataItemTest.ParsingWithoutFormatReturnsZero]=]  /path/to/asterix/bin/test_dataitem [==[--gtest_filter=DataItemTest.ParsingWithoutFormatReturnsZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataItemTest.ParsingWithoutFormatReturnsZero]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataItemTest.ParsingWithInsufficientData]=]  /path/to/asterix/bin/test_dataitem [==[--gtest_filter=DataItemTest.ParsingWithInsufficientData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataItemTest.ParsingWithInsufficientData]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataItemTest.ParsingWithEmptyData]=]  /path/to/asterix/bin/test_dataitem [==[--gtest_filter=DataItemTest.ParsingWithEmptyData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataItemTest.ParsingWithEmptyData]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataItemTest.GetTextReturnsRepresentation]=]  /path/to/asterix/bin/test_dataitem [==[--gtest_filter=DataItemTest.GetTextReturnsRepresentation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataItemTest.GetTextReturnsRepresentation]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataItemTest.DataSourceIdentifierDescription]=]  /path/to/asterix/bin/test_dataitem [==[--gtest_filter=DataItemTest.DataSourceIdentifierDescription]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataItemTest.DataSourceIdentifierDescription]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataItemTest.MultipleDataItemsCoexist]=]  /path/to/asterix/bin/test_dataitem [==[--gtest_filter=DataItemTest.MultipleDataItemsCoexist]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataItemTest.MultipleDataItemsCoexist]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataItemTest.DestructorCleansUp]=]  /path/to/asterix/bin/test_dataitem [==[--gtest_filter=DataItemTest.DestructorCleansUp]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataItemTest.DestructorCleansUp]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_dataitem_TESTS DataItemTest.ConstructorInitializes DataItemTest.InitialLengthIsZero DataItemTest.NullDescriptionHandled DataItemTest.ParsingWithoutFormatReturnsZero DataItemTest.ParsingWithInsufficientData DataItemTest.ParsingWithEmptyData DataItemTest.GetTextReturnsRepresentation DataItemTest.DataSourceIdentifierDescription DataItemTest.MultipleDataItemsCoexist DataItemTest.DestructorCleansUp)
