if(EXISTS "/path/to/asterix/tests/cpp/test_asterixdata[1]_tests.cmake")
  include("/path/to/asterix/tests/cpp/test_asterixdata[1]_tests.cmake")
else()
  add_test(test_asterixdata_NOT_BUILT test_asterixdata_NOT_BUILT)
endif()
