add_test([=[DataRecordTest.ConstructorSingleFSPECSingleItem]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.ConstructorSingleFSPECSingleItem]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.ConstructorSingleFSPECSingleItem]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.ConstructorMultiByteFSPEC]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.ConstructorMultiByteFSPEC]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.ConstructorMultiByteFSPEC]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.ConstructorNoUAP]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.ConstructorNoUAP]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.ConstructorNoUAP]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.ConstructorMissingDescription]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.ConstructorMissingDescription]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.ConstructorMissingDescription]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.ConstructorNullFormat]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.ConstructorNullFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.ConstructorNullFormat]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.ConstructorInsufficientData]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.ConstructorInsufficientData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.ConstructorInsufficientData]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.ConstructorUnparsedBytes]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.ConstructorUnparsedBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.ConstructorUnparsedBytes]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetTextFormatText]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetTextFormatText]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetTextFormatText]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetTextFormatJSON]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetTextFormatJSON]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetTextFormatJSON]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetTextFormatJSONH]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetTextFormatJSONH]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetTextFormatJSONH]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetTextFormatJSONE]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetTextFormatJSONE]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetTextFormatJSONE]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetTextFormatXML]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetTextFormatXML]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetTextFormatXML]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetTextFormatXMLH]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetTextFormatXMLH]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetTextFormatXMLH]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetTextFormatNotOK]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetTextFormatNotOK]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetTextFormatNotOK]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetItemExisting]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetItemExisting]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetItemExisting]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetItemNonExisting]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetItemNonExisting]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetItemNonExisting]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetCategory]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetCategory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetCategory]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.DestructorCleanup]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.DestructorCleanup]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.DestructorCleanup]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.MultipleFSPECManyItems]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.MultipleFSPECManyItems]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.MultipleFSPECManyItems]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetTextMultipleItemsCommaSeparation]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetTextMultipleItemsCommaSeparation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetTextMultipleItemsCommaSeparation]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.CRCCalculation]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.CRCCalculation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.CRCCalculation]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.HexDataGeneration]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.HexDataGeneration]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.HexDataGeneration]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.EmptyFSPEC]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.EmptyFSPEC]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.EmptyFSPEC]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.FSPECOnlyExtensions]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.FSPECOnlyExtensions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.FSPECOnlyExtensions]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.TimestampPreservation]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.TimestampPreservation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.TimestampPreservation]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.FSPECItemDescriptionNotFound]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.FSPECItemDescriptionNotFound]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.FSPECItemDescriptionNotFound]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.NegativeUnparsedBytes]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.NegativeUnparsedBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.NegativeUnparsedBytes]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetTextWithFormatNotOK]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetTextWithFormatNotOK]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetTextWithFormatNotOK]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetTextJSONHMultipleItemsComma]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetTextJSONHMultipleItemsComma]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetTextJSONHMultipleItemsComma]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetTextJSONEMultipleItems]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetTextJSONEMultipleItems]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetTextJSONEMultipleItems]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.ThreeByteFSPEC]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.ThreeByteFSPEC]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.ThreeByteFSPEC]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.FourByteFSPEC]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.FourByteFSPEC]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.FourByteFSPEC]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.FSPECSparseItems]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.FSPECSparseItems]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.FSPECSparseItems]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.RecordWithManyItems]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.RecordWithManyItems]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.RecordWithManyItems]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetTextAllFormats]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetTextAllFormats]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetTextAllFormats]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.GetItemMultipleIterations]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.GetItemMultipleIterations]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.GetItemMultipleIterations]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.HexDataVariousPatterns]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.HexDataVariousPatterns]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.HexDataVariousPatterns]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.CRCDifferentData]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.CRCDifferentData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.CRCDifferentData]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.ZeroTimestamp]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.ZeroTimestamp]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.ZeroTimestamp]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.NegativeTimestamp]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.NegativeTimestamp]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.NegativeTimestamp]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.DestructorEmptyList]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.DestructorEmptyList]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.DestructorEmptyList]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.FSPECAllBitsExceptFX]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.FSPECAllBitsExceptFX]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.FSPECAllBitsExceptFX]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.FSPECAlternatingBits]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.FSPECAlternatingBits]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.FSPECAlternatingBits]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.LargeRecordID]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.LargeRecordID]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.LargeRecordID]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.MultipleUnparsedBytes]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.MultipleUnparsedBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.MultipleUnparsedBytes]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.UAPItemLookupFailure]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.UAPItemLookupFailure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.UAPItemLookupFailure]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataRecordTest.InsufficientDataNoErrorFlag]=]  /path/to/asterix/bin/test_datarecord [==[--gtest_filter=DataRecordTest.InsufficientDataNoErrorFlag]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataRecordTest.InsufficientDataNoErrorFlag]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_datarecord_TESTS DataRecordTest.ConstructorSingleFSPECSingleItem DataRecordTest.ConstructorMultiByteFSPEC DataRecordTest.ConstructorNoUAP DataRecordTest.ConstructorMissingDescription DataRecordTest.ConstructorNullFormat DataRecordTest.ConstructorInsufficientData DataRecordTest.ConstructorUnparsedBytes DataRecordTest.GetTextFormatText DataRecordTest.GetTextFormatJSON DataRecordTest.GetTextFormatJSONH DataRecordTest.GetTextFormatJSONE DataRecordTest.GetTextFormatXML DataRecordTest.GetTextFormatXMLH DataRecordTest.GetTextFormatNotOK DataRecordTest.GetItemExisting DataRecordTest.GetItemNonExisting DataRecordTest.GetCategory DataRecordTest.DestructorCleanup DataRecordTest.MultipleFSPECManyItems DataRecordTest.GetTextMultipleItemsCommaSeparation DataRecordTest.CRCCalculation DataRecordTest.HexDataGeneration DataRecordTest.EmptyFSPEC DataRecordTest.FSPECOnlyExtensions DataRecordTest.TimestampPreservation DataRecordTest.FSPECItemDescriptionNotFound DataRecordTest.NegativeUnparsedBytes DataRecordTest.GetTextWithFormatNotOK DataRecordTest.GetTextJSONHMultipleItemsComma DataRecordTest.GetTextJSONEMultipleItems DataRecordTest.ThreeByteFSPEC DataRecordTest.FourByteFSPEC DataRecordTest.FSPECSparseItems DataRecordTest.RecordWithManyItems DataRecordTest.GetTextAllFormats DataRecordTest.GetItemMultipleIterations DataRecordTest.HexDataVariousPatterns DataRecordTest.CRCDifferentData DataRecordTest.ZeroTimestamp DataRecordTest.NegativeTimestamp DataRecordTest.DestructorEmptyList DataRecordTest.FSPECAllBitsExceptFX DataRecordTest.FSPECAlternatingBits DataRecordTest.LargeRecordID DataRecordTest.MultipleUnparsedBytes DataRecordTest.UAPItemLookupFailure DataRecordTest.InsufficientDataNoErrorFlag)
