if(EXISTS "/home/e/Development/asterix/tests/cpp/test_uap[1]_tests.cmake")
  include("/home/e/Development/asterix/tests/cpp/test_uap[1]_tests.cmake")
else()
  add_test(test_uap_NOT_BUILT test_uap_NOT_BUILT)
endif()
