add_test([=[XMLParserTest.ParseSimpleFixedCategory]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseSimpleFixedCategory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseSimpleFixedCategory]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseVariableFormat]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseVariableFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseVariableFormat]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseCompoundFormat]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseCompoundFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseCompoundFormat]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseRepetitiveFormat]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseRepetitiveFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseRepetitiveFormat]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseExplicitFormat]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseExplicitFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseExplicitFormat]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseBitsValue]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseBitsValue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseBitsValue]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseBitsUnit]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseBitsUnit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseBitsUnit]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseMultipleDataItems]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseMultipleDataItems]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseMultipleDataItems]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseUAPDefinition]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseUAPDefinition]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseUAPDefinition]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseBitsConst]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseBitsConst]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseBitsConst]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.MissingFileError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.MissingFileError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.MissingFileError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.MalformedXMLError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.MalformedXMLError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.MalformedXMLError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.InvalidCategoryID]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.InvalidCategoryID]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.InvalidCategoryID]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.DataItemWithoutCategory]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.DataItemWithoutCategory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.DataItemWithoutCategory]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.BitsWithoutFormat]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.BitsWithoutFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.BitsWithoutFormat]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.BitsWithoutFixed]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.BitsWithoutFixed]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.BitsWithoutFixed]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.EmptyXMLFile]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.EmptyXMLFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.EmptyXMLFile]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.XMLWithoutDoctype]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.XMLWithoutDoctype]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.XMLWithoutDoctype]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.DuplicateFormatError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.DuplicateFormatError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.DuplicateFormatError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.NestedCompoundFormat]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.NestedCompoundFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.NestedCompoundFormat]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseBDSCategory]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseBDSCategory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseBDSCategory]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseBitEncodings]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseBitEncodings]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseBitEncodings]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.BitOutOfRangeError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.BitOutOfRangeError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.BitOutOfRangeError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseExplicitWithVariable]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseExplicitWithVariable]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseExplicitWithVariable]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseExplicitWithRepetitive]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseExplicitWithRepetitive]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseExplicitWithRepetitive]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseMultipleUAPs]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseMultipleUAPs]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseMultipleUAPs]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.UnknownTagError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.UnknownTagError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.UnknownTagError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ClosingUnopenedTagError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ClosingUnopenedTagError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ClosingUnopenedTagError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseFXBitAttribute]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseFXBitAttribute]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseFXBitAttribute]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.CategoryWithNoDataItems]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.CategoryWithNoDataItems]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.CategoryWithNoDataItems]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.CompoundWithoutVariableFirstError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.CompoundWithoutVariableFirstError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.CompoundWithoutVariableFirstError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseDataItemWithNote]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseDataItemWithNote]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseDataItemWithNote]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseDataItemRules]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseDataItemRules]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseDataItemRules]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseCompoundWithinCompound]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseCompoundWithinCompound]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseCompoundWithinCompound]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseExplicitWithCompound]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseExplicitWithCompound]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseExplicitWithCompound]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseHexEncoding]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseHexEncoding]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseHexEncoding]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseUAPItemWithLen]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseUAPItemWithLen]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseUAPItemWithLen]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseRepetitiveInExplicit]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseRepetitiveInExplicit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseRepetitiveInExplicit]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseVariableInExplicit]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseVariableInExplicit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseVariableInExplicit]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseAllEncodings]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseAllEncodings]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseAllEncodings]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.WrongEncodeAttributeError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.WrongEncodeAttributeError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.WrongEncodeAttributeError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.UnknownCategoryAttributeError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.UnknownCategoryAttributeError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.UnknownCategoryAttributeError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.UnknownDataItemAttributeError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.UnknownDataItemAttributeError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.UnknownDataItemAttributeError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.UnknownFormatAttributeError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.UnknownFormatAttributeError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.UnknownFormatAttributeError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.UnknownFixedAttributeError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.UnknownFixedAttributeError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.UnknownFixedAttributeError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.UnknownBitsAttributeError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.UnknownBitsAttributeError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.UnknownBitsAttributeError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.UnknownUAPAttributeError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.UnknownUAPAttributeError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.UnknownUAPAttributeError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.UnknownUAPItemAttributeError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.UnknownUAPItemAttributeError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.UnknownUAPItemAttributeError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.ParseBitsName]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.ParseBitsName]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.ParseBitsName]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.NegativeBitValueError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.NegativeBitValueError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.NegativeBitValueError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.NegativeFixedLengthError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.NegativeFixedLengthError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.NegativeFixedLengthError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.FormatWithoutDataItemError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.FormatWithoutDataItemError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.FormatWithoutDataItemError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.UAPItemWithoutUAPError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.UAPItemWithoutUAPError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.UAPItemWithoutUAPError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.UAPWithoutCategoryError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.UAPWithoutCategoryError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.UAPWithoutCategoryError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.BitsValueWithoutBitsError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.BitsValueWithoutBitsError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.BitsValueWithoutBitsError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.BitsUnitWithoutBitsError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.BitsUnitWithoutBitsError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.BitsUnitWithoutBitsError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XMLParserTest.BitsConstWithoutBitsError]=]  /path/to/asterix/bin/test_xmlparser [==[--gtest_filter=XMLParserTest.BitsConstWithoutBitsError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XMLParserTest.BitsConstWithoutBitsError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_xmlparser_TESTS XMLParserTest.ParseSimpleFixedCategory XMLParserTest.ParseVariableFormat XMLParserTest.ParseCompoundFormat XMLParserTest.ParseRepetitiveFormat XMLParserTest.ParseExplicitFormat XMLParserTest.ParseBitsValue XMLParserTest.ParseBitsUnit XMLParserTest.ParseMultipleDataItems XMLParserTest.ParseUAPDefinition XMLParserTest.ParseBitsConst XMLParserTest.MissingFileError XMLParserTest.MalformedXMLError XMLParserTest.InvalidCategoryID XMLParserTest.DataItemWithoutCategory XMLParserTest.BitsWithoutFormat XMLParserTest.BitsWithoutFixed XMLParserTest.EmptyXMLFile XMLParserTest.XMLWithoutDoctype XMLParserTest.DuplicateFormatError XMLParserTest.NestedCompoundFormat XMLParserTest.ParseBDSCategory XMLParserTest.ParseBitEncodings XMLParserTest.BitOutOfRangeError XMLParserTest.ParseExplicitWithVariable XMLParserTest.ParseExplicitWithRepetitive XMLParserTest.ParseMultipleUAPs XMLParserTest.UnknownTagError XMLParserTest.ClosingUnopenedTagError XMLParserTest.ParseFXBitAttribute XMLParserTest.CategoryWithNoDataItems XMLParserTest.CompoundWithoutVariableFirstError XMLParserTest.ParseDataItemWithNote XMLParserTest.ParseDataItemRules XMLParserTest.ParseCompoundWithinCompound XMLParserTest.ParseExplicitWithCompound XMLParserTest.ParseHexEncoding XMLParserTest.ParseUAPItemWithLen XMLParserTest.ParseRepetitiveInExplicit XMLParserTest.ParseVariableInExplicit XMLParserTest.ParseAllEncodings XMLParserTest.WrongEncodeAttributeError XMLParserTest.UnknownCategoryAttributeError XMLParserTest.UnknownDataItemAttributeError XMLParserTest.UnknownFormatAttributeError XMLParserTest.UnknownFixedAttributeError XMLParserTest.UnknownBitsAttributeError XMLParserTest.UnknownUAPAttributeError XMLParserTest.UnknownUAPItemAttributeError XMLParserTest.ParseBitsName XMLParserTest.NegativeBitValueError XMLParserTest.NegativeFixedLengthError XMLParserTest.FormatWithoutDataItemError XMLParserTest.UAPItemWithoutUAPError XMLParserTest.UAPWithoutCategoryError XMLParserTest.BitsValueWithoutBitsError XMLParserTest.BitsUnitWithoutBitsError XMLParserTest.BitsConstWithoutBitsError)
