add_test([=[CAT065IntegrationTest.LoadXMLConfiguration]=]  /path/to/asterix/bin/test_integration_cat065 [==[--gtest_filter=CAT065IntegrationTest.LoadXMLConfiguration]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CAT065IntegrationTest.LoadXMLConfiguration]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CAT065IntegrationTest.ParseCAT065BinaryData]=]  /path/to/asterix/bin/test_integration_cat065 [==[--gtest_filter=CAT065IntegrationTest.ParseCAT065BinaryData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CAT065IntegrationTest.ParseCAT065BinaryData]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CAT065IntegrationTest.VerifyParsedDataStructure]=]  /path/to/asterix/bin/test_integration_cat065 [==[--gtest_filter=CAT065IntegrationTest.VerifyParsedDataStructure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CAT065IntegrationTest.VerifyParsedDataStructure]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CAT065IntegrationTest.RejectInvalidData]=]  /path/to/asterix/bin/test_integration_cat065 [==[--gtest_filter=CAT065IntegrationTest.RejectInvalidData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CAT065IntegrationTest.RejectInvalidData]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CAT065IntegrationTest.VerifyTextOutput]=]  /path/to/asterix/bin/test_integration_cat065 [==[--gtest_filter=CAT065IntegrationTest.VerifyTextOutput]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CAT065IntegrationTest.VerifyTextOutput]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_integration_cat065_TESTS CAT065IntegrationTest.LoadXMLConfiguration CAT065IntegrationTest.ParseCAT065BinaryData CAT065IntegrationTest.VerifyParsedDataStructure CAT065IntegrationTest.RejectInvalidData CAT065IntegrationTest.VerifyTextOutput)
