add_test([=[DataBlockTest.ConstructorSingleRecord]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.ConstructorSingleRecord]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.ConstructorSingleRecord]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.ConstructorMultipleRecords]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.ConstructorMultipleRecords]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.ConstructorMultipleRecords]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.ConstructorWithTimestamp]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.ConstructorWithTimestamp]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.ConstructorWithTimestamp]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.ConstructorWithFilteredCategory]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.ConstructorWithFilteredCategory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.ConstructorWithFilteredCategory]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.ConstructorWithCategoryInFilter]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.ConstructorWithCategoryInFilter]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.ConstructorWithCategoryInFilter]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.DestructorCleansUpRecords]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.DestructorCleansUpRecords]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.DestructorCleansUpRecords]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.GetTextFormatText]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.GetTextFormatText]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.GetTextFormatText]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.GetTextFormatOut]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.GetTextFormatOut]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.GetTextFormatOut]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.GetTextFormatJSON]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.GetTextFormatJSON]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.GetTextFormatJSON]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.GetTextFormatJSONH]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.GetTextFormatJSONH]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.GetTextFormatJSONH]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.GetTextFormatXML]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.GetTextFormatXML]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.GetTextFormatXML]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.GetTextFormatXMLH]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.GetTextFormatXMLH]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.GetTextFormatXMLH]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.GetTextWithFilteredCategory]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.GetTextWithFilteredCategory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.GetTextWithFilteredCategory]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.GetTextWithFormatNotOK]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.GetTextWithFormatNotOK]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.GetTextWithFormatNotOK]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.GetTextWithEmptyRecords]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.GetTextWithEmptyRecords]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.GetTextWithEmptyRecords]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.ConstructorZeroLengthData]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.ConstructorZeroLengthData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.ConstructorZeroLengthData]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.ConstructorWithUnparsedData]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.ConstructorWithUnparsedData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.ConstructorWithUnparsedData]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.ConstructorManyRecords]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.ConstructorManyRecords]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.ConstructorManyRecords]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.CategoryPointerPreserved]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.CategoryPointerPreserved]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.CategoryPointerPreserved]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DataBlockTest.GetTextWithMultipleRecords]=]  /path/to/asterix/bin/test_datablock [==[--gtest_filter=DataBlockTest.GetTextWithMultipleRecords]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DataBlockTest.GetTextWithMultipleRecords]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_datablock_TESTS DataBlockTest.ConstructorSingleRecord DataBlockTest.ConstructorMultipleRecords DataBlockTest.ConstructorWithTimestamp DataBlockTest.ConstructorWithFilteredCategory DataBlockTest.ConstructorWithCategoryInFilter DataBlockTest.DestructorCleansUpRecords DataBlockTest.GetTextFormatText DataBlockTest.GetTextFormatOut DataBlockTest.GetTextFormatJSON DataBlockTest.GetTextFormatJSONH DataBlockTest.GetTextFormatXML DataBlockTest.GetTextFormatXMLH DataBlockTest.GetTextWithFilteredCategory DataBlockTest.GetTextWithFormatNotOK DataBlockTest.GetTextWithEmptyRecords DataBlockTest.ConstructorZeroLengthData DataBlockTest.ConstructorWithUnparsedData DataBlockTest.ConstructorManyRecords DataBlockTest.CategoryPointerPreserved DataBlockTest.GetTextWithMultipleRecords)
