add_test([=[TracerTest.SingletonInstanceNotNull]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.SingletonInstanceNotNull]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.SingletonInstanceNotNull]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.SingletonReturnsSameInstance]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.SingletonReturnsSameInstance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.SingletonReturnsSameInstance]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.GlobalInstancePointer]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.GlobalInstancePointer]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.GlobalInstancePointer]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.ErrorMessageDefaultHandler]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.ErrorMessageDefaultHandler]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.ErrorMessageDefaultHandler]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.ErrorMessageWithFormatString]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.ErrorMessageWithFormatString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.ErrorMessageWithFormatString]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.MultipleErrorCalls]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.MultipleErrorCalls]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.MultipleErrorCalls]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.ConfigureWithPrintfCallback]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.ConfigureWithPrintfCallback]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.ConfigureWithPrintfCallback]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.ConfigureWithVoidPrintfCallback]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.ConfigureWithVoidPrintfCallback]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.ConfigureWithVoidPrintfCallback]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.ErrorUsesConfiguredPrintfCallback]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.ErrorUsesConfiguredPrintfCallback]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.ErrorUsesConfiguredPrintfCallback]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.ErrorUsesConfiguredVoidPrintfCallback]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.ErrorUsesConfiguredVoidPrintfCallback]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.ErrorUsesConfiguredVoidPrintfCallback]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.CallbackPriority]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.CallbackPriority]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.CallbackPriority]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.DeleteClearsSingleton]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.DeleteClearsSingleton]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.DeleteClearsSingleton]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.RecreateAfterDelete]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.RecreateAfterDelete]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.RecreateAfterDelete]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.ErrorHandlesLongMessage]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.ErrorHandlesLongMessage]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.ErrorHandlesLongMessage]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.ErrorHandlesEmptyMessage]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.ErrorHandlesEmptyMessage]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.ErrorHandlesEmptyMessage]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.ErrorWithSpecialCharacters]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.ErrorWithSpecialCharacters]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.ErrorWithSpecialCharacters]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.ErrorWithHexFormat]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.ErrorWithHexFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.ErrorWithHexFormat]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.ConstructorInitializesCallbacks]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.ConstructorInitializesCallbacks]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.ConstructorInitializesCallbacks]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.RapidRepeatedCalls]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.RapidRepeatedCalls]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.RapidRepeatedCalls]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.ErrorWithFloatFormat]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.ErrorWithFloatFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.ErrorWithFloatFormat]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TracerTest.CallbackCanBeChanged]=]  /home/e/Development/asterix/bin/test_tracer [==[--gtest_filter=TracerTest.CallbackCanBeChanged]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TracerTest.CallbackCanBeChanged]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_tracer_TESTS TracerTest.SingletonInstanceNotNull TracerTest.SingletonReturnsSameInstance TracerTest.GlobalInstancePointer TracerTest.ErrorMessageDefaultHandler TracerTest.ErrorMessageWithFormatString TracerTest.MultipleErrorCalls TracerTest.ConfigureWithPrintfCallback TracerTest.ConfigureWithVoidPrintfCallback TracerTest.ErrorUsesConfiguredPrintfCallback TracerTest.ErrorUsesConfiguredVoidPrintfCallback TracerTest.CallbackPriority TracerTest.DeleteClearsSingleton TracerTest.RecreateAfterDelete TracerTest.ErrorHandlesLongMessage TracerTest.ErrorHandlesEmptyMessage TracerTest.ErrorWithSpecialCharacters TracerTest.ErrorWithHexFormat TracerTest.ConstructorInitializesCallbacks TracerTest.RapidRepeatedCalls TracerTest.ErrorWithFloatFormat TracerTest.CallbackCanBeChanged)
