if(EXISTS "/path/to/asterix/tests/cpp/test_utils[1]_tests.cmake")
  include("/path/to/asterix/tests/cpp/test_utils[1]_tests.cmake")
else()
  add_test(test_utils_NOT_BUILT test_utils_NOT_BUILT)
endif()
