if(EXISTS "/path/to/asterix/tests/cpp/test_dataitem[1]_tests.cmake")
  include("/path/to/asterix/tests/cpp/test_dataitem[1]_tests.cmake")
else()
  add_test(test_dataitem_NOT_BUILT test_dataitem_NOT_BUILT)
endif()
