if(EXISTS "/home/e/Development/asterix/tests/cpp/test_dataitemformatrepetitive[1]_tests.cmake")
  include("/home/e/Development/asterix/tests/cpp/test_dataitemformatrepetitive[1]_tests.cmake")
else()
  add_test(test_dataitemformatrepetitive_NOT_BUILT test_dataitemformatrepetitive_NOT_BUILT)
endif()
