add_test([=[AsterixDataTest.ConstructorInitializesEmptyContainer]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.ConstructorInitializesEmptyContainer]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.ConstructorInitializesEmptyContainer]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.AddSingleDataBlock]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.AddSingleDataBlock]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.AddSingleDataBlock]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.AddMultipleDataBlocks]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.AddMultipleDataBlocks]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.AddMultipleDataBlocks]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.DestructorCleansUpDataBlocks]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.DestructorCleansUpDataBlocks]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.DestructorCleansUpDataBlocks]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.IterateOverDataBlocks]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.IterateOverDataBlocks]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.IterateOverDataBlocks]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.GetTextWithEmptyContainer]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.GetTextWithEmptyContainer]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.GetTextWithEmptyContainer]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.GetTextWithSingleBlockTextFormat]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.GetTextWithSingleBlockTextFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.GetTextWithSingleBlockTextFormat]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.GetTextWithMultipleBlocks]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.GetTextWithMultipleBlocks]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.GetTextWithMultipleBlocks]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.GetTextWithJSONFormat]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.GetTextWithJSONFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.GetTextWithJSONFormat]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.GetTextWithXMLFormat]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.GetTextWithXMLFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.GetTextWithXMLFormat]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.ClearContainer]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.ClearContainer]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.ClearContainer]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.HandleNullDataBlockInList]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.HandleNullDataBlockInList]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.HandleNullDataBlockInList]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.LargeNumberOfDataBlocks]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.LargeNumberOfDataBlocks]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.LargeNumberOfDataBlocks]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.DestructorWithEmptyList]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.DestructorWithEmptyList]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.DestructorWithEmptyList]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.DestructorIterationCleanup]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.DestructorIterationCleanup]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.DestructorIterationCleanup]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.GetTextIncrementsBlockCounter]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.GetTextIncrementsBlockCounter]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.GetTextIncrementsBlockCounter]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.GetTextWithAllFormatTypes]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.GetTextWithAllFormatTypes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.GetTextWithAllFormatTypes]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AsterixDataTest.MoveDataBlocksList]=]  /path/to/asterix/bin/test_asterixdata [==[--gtest_filter=AsterixDataTest.MoveDataBlocksList]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsterixDataTest.MoveDataBlocksList]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_asterixdata_TESTS AsterixDataTest.ConstructorInitializesEmptyContainer AsterixDataTest.AddSingleDataBlock AsterixDataTest.AddMultipleDataBlocks AsterixDataTest.DestructorCleansUpDataBlocks AsterixDataTest.IterateOverDataBlocks AsterixDataTest.GetTextWithEmptyContainer AsterixDataTest.GetTextWithSingleBlockTextFormat AsterixDataTest.GetTextWithMultipleBlocks AsterixDataTest.GetTextWithJSONFormat AsterixDataTest.GetTextWithXMLFormat AsterixDataTest.ClearContainer AsterixDataTest.HandleNullDataBlockInList AsterixDataTest.LargeNumberOfDataBlocks AsterixDataTest.DestructorWithEmptyList AsterixDataTest.DestructorIterationCleanup AsterixDataTest.GetTextIncrementsBlockCounter AsterixDataTest.GetTextWithAllFormatTypes AsterixDataTest.MoveDataBlocksList)
