if(EXISTS "/path/to/asterix/tests/cpp/test_tracer[1]_tests.cmake")
  include("/path/to/asterix/tests/cpp/test_tracer[1]_tests.cmake")
else()
  add_test(test_tracer_NOT_BUILT test_tracer_NOT_BUILT)
endif()
