add_test([=[PCAPFormatTest.ValidatePCAPFileStructure]=]  /home/e/Development/asterix/bin/test_integration_pcap_format [==[--gtest_filter=PCAPFormatTest.ValidatePCAPFileStructure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PCAPFormatTest.ValidatePCAPFileStructure]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PCAPFormatTest.FindASTERIXInPCAP]=]  /home/e/Development/asterix/bin/test_integration_pcap_format [==[--gtest_filter=PCAPFormatTest.FindASTERIXInPCAP]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PCAPFormatTest.FindASTERIXInPCAP]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PCAPFormatTest.VerifyPCAPPacketHeaders]=]  /home/e/Development/asterix/bin/test_integration_pcap_format [==[--gtest_filter=PCAPFormatTest.VerifyPCAPPacketHeaders]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PCAPFormatTest.VerifyPCAPPacketHeaders]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PCAPFormatTest.HandleSmallPCAPFile]=]  /home/e/Development/asterix/bin/test_integration_pcap_format [==[--gtest_filter=PCAPFormatTest.HandleSmallPCAPFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PCAPFormatTest.HandleSmallPCAPFile]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PCAPFormatTest.HandleLargerPCAPFile]=]  /home/e/Development/asterix/bin/test_integration_pcap_format [==[--gtest_filter=PCAPFormatTest.HandleLargerPCAPFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PCAPFormatTest.HandleLargerPCAPFile]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_integration_pcap_format_TESTS PCAPFormatTest.ValidatePCAPFileStructure PCAPFormatTest.FindASTERIXInPCAP PCAPFormatTest.VerifyPCAPPacketHeaders PCAPFormatTest.HandleSmallPCAPFile PCAPFormatTest.HandleLargerPCAPFile)
