if(EXISTS "/path/to/asterix/tests/cpp/test_dataitemformatvariable[1]_tests.cmake")
  include("/path/to/asterix/tests/cpp/test_dataitemformatvariable[1]_tests.cmake")
else()
  add_test(test_dataitemformatvariable_NOT_BUILT test_dataitemformatvariable_NOT_BUILT)
endif()
