add_test([=[UtilsTest.CRC32EmptyData]=]  /home/e/Development/asterix/bin/test_utils [==[--gtest_filter=UtilsTest.CRC32EmptyData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UtilsTest.CRC32EmptyData]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UtilsTest.CRC32KnownData]=]  /home/e/Development/asterix/bin/test_utils [==[--gtest_filter=UtilsTest.CRC32KnownData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UtilsTest.CRC32KnownData]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UtilsTest.CRC32BinaryData]=]  /home/e/Development/asterix/bin/test_utils [==[--gtest_filter=UtilsTest.CRC32BinaryData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UtilsTest.CRC32BinaryData]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UtilsTest.CRC32DifferentDataDifferentCRC]=]  /home/e/Development/asterix/bin/test_utils [==[--gtest_filter=UtilsTest.CRC32DifferentDataDifferentCRC]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UtilsTest.CRC32DifferentDataDifferentCRC]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UtilsTest.CRC32WithPreviousCRC]=]  /home/e/Development/asterix/bin/test_utils [==[--gtest_filter=UtilsTest.CRC32WithPreviousCRC]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UtilsTest.CRC32WithPreviousCRC]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UtilsTest.CRC32DetectsCorruption]=]  /home/e/Development/asterix/bin/test_utils [==[--gtest_filter=UtilsTest.CRC32DetectsCorruption]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UtilsTest.CRC32DetectsCorruption]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UtilsTest.FormatSimpleString]=]  /home/e/Development/asterix/bin/test_utils [==[--gtest_filter=UtilsTest.FormatSimpleString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UtilsTest.FormatSimpleString]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UtilsTest.FormatWithInteger]=]  /home/e/Development/asterix/bin/test_utils [==[--gtest_filter=UtilsTest.FormatWithInteger]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UtilsTest.FormatWithInteger]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UtilsTest.FormatWithMultipleParameters]=]  /home/e/Development/asterix/bin/test_utils [==[--gtest_filter=UtilsTest.FormatWithMultipleParameters]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UtilsTest.FormatWithMultipleParameters]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UtilsTest.FormatWithHexValues]=]  /home/e/Development/asterix/bin/test_utils [==[--gtest_filter=UtilsTest.FormatWithHexValues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UtilsTest.FormatWithHexValues]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UtilsTest.FormatWithFloat]=]  /home/e/Development/asterix/bin/test_utils [==[--gtest_filter=UtilsTest.FormatWithFloat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UtilsTest.FormatWithFloat]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UtilsTest.CRC32LargeData]=]  /home/e/Development/asterix/bin/test_utils [==[--gtest_filter=UtilsTest.CRC32LargeData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UtilsTest.CRC32LargeData]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UtilsTest.CRC32ASTERIXPacket]=]  /home/e/Development/asterix/bin/test_utils [==[--gtest_filter=UtilsTest.CRC32ASTERIXPacket]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UtilsTest.CRC32ASTERIXPacket]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_utils_TESTS UtilsTest.CRC32EmptyData UtilsTest.CRC32KnownData UtilsTest.CRC32BinaryData UtilsTest.CRC32DifferentDataDifferentCRC UtilsTest.CRC32WithPreviousCRC UtilsTest.CRC32DetectsCorruption UtilsTest.FormatSimpleString UtilsTest.FormatWithInteger UtilsTest.FormatWithMultipleParameters UtilsTest.FormatWithHexValues UtilsTest.FormatWithFloat UtilsTest.CRC32LargeData UtilsTest.CRC32ASTERIXPacket)
