if(EXISTS "/path/to/asterix/tests/cpp/test_dataitemformatexplicit[1]_tests.cmake")
  include("/path/to/asterix/tests/cpp/test_dataitemformatexplicit[1]_tests.cmake")
else()
  add_test(test_dataitemformatexplicit_NOT_BUILT test_dataitemformatexplicit_NOT_BUILT)
endif()
