add_test([=[UAPTest.ConstructorInitialization]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.ConstructorInitialization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.ConstructorInitialization]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.NewUAPItemCreatesAndAdds]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.NewUAPItemCreatesAndAdds]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.NewUAPItemCreatesAndAdds]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.MultipleUAPItemsCanBeAdded]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.MultipleUAPItemsCanBeAdded]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.MultipleUAPItemsCanBeAdded]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.GetDataItemIDByValidFRN]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.GetDataItemIDByValidFRN]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.GetDataItemIDByValidFRN]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.GetDataItemIDByInvalidFRN]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.GetDataItemIDByInvalidFRN]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.GetDataItemIDByInvalidFRN]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.GetDataItemIDByFRNEmptyUAP]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.GetDataItemIDByFRNEmptyUAP]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.GetDataItemIDByFRNEmptyUAP]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.GetDataItemIDByFRNZero]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.GetDataItemIDByFRNZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.GetDataItemIDByFRNZero]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.GetDataItemIDByFRNDuplicateFRNs]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.GetDataItemIDByFRNDuplicateFRNs]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.GetDataItemIDByFRNDuplicateFRNs]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.DestructorCleansUpItems]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.DestructorCleansUpItems]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.DestructorCleansUpItems]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.ConditionalUAPUseIfBitSet]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.ConditionalUAPUseIfBitSet]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.ConditionalUAPUseIfBitSet]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.UAPItemListOrderPreserved]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.UAPItemListOrderPreserved]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.UAPItemListOrderPreserved]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.CAT048TypicalUAP]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.CAT048TypicalUAP]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.CAT048TypicalUAP]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.CAT062TypicalUAP]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.CAT062TypicalUAP]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.CAT062TypicalUAP]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.UAPWithFXItems]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.UAPWithFXItems]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.UAPWithFXItems]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.GetDataItemIDByLargeFRN]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.GetDataItemIDByLargeFRN]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.GetDataItemIDByLargeFRN]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.GetDataItemIDByNegativeFRN]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.GetDataItemIDByNegativeFRN]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.GetDataItemIDByNegativeFRN]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.MultipleCreateDestroyCycles]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.MultipleCreateDestroyCycles]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.MultipleCreateDestroyCycles]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.UAPWithMaximumTypicalFRNs]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.UAPWithMaximumTypicalFRNs]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.UAPWithMaximumTypicalFRNs]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.DefaultUAPConditionals]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.DefaultUAPConditionals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.DefaultUAPConditionals]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.SparseUAPMapping]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.SparseUAPMapping]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.SparseUAPMapping]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.UAPItemListIteration]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.UAPItemListIteration]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.UAPItemListIteration]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPTest.EmptyUAPDestruction]=]  /home/e/Development/asterix/bin/test_uap [==[--gtest_filter=UAPTest.EmptyUAPDestruction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPTest.EmptyUAPDestruction]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_uap_TESTS UAPTest.ConstructorInitialization UAPTest.NewUAPItemCreatesAndAdds UAPTest.MultipleUAPItemsCanBeAdded UAPTest.GetDataItemIDByValidFRN UAPTest.GetDataItemIDByInvalidFRN UAPTest.GetDataItemIDByFRNEmptyUAP UAPTest.GetDataItemIDByFRNZero UAPTest.GetDataItemIDByFRNDuplicateFRNs UAPTest.DestructorCleansUpItems UAPTest.ConditionalUAPUseIfBitSet UAPTest.UAPItemListOrderPreserved UAPTest.CAT048TypicalUAP UAPTest.CAT062TypicalUAP UAPTest.UAPWithFXItems UAPTest.GetDataItemIDByLargeFRN UAPTest.GetDataItemIDByNegativeFRN UAPTest.MultipleCreateDestroyCycles UAPTest.UAPWithMaximumTypicalFRNs UAPTest.DefaultUAPConditionals UAPTest.SparseUAPMapping UAPTest.UAPItemListIteration UAPTest.EmptyUAPDestruction)
