if(EXISTS "/home/e/Development/asterix/tests/cpp/test_dataitembits[1]_tests.cmake")
  include("/home/e/Development/asterix/tests/cpp/test_dataitembits[1]_tests.cmake")
else()
  add_test(test_dataitembits_NOT_BUILT test_dataitembits_NOT_BUILT)
endif()
