if(EXISTS "/home/e/Development/asterix/tests/cpp/test_xmlparser[1]_tests.cmake")
  include("/home/e/Development/asterix/tests/cpp/test_xmlparser[1]_tests.cmake")
else()
  add_test(test_xmlparser_NOT_BUILT test_xmlparser_NOT_BUILT)
endif()
