if(EXISTS "/path/to/asterix/tests/cpp/test_integration_pcap_format[1]_tests.cmake")
  include("/path/to/asterix/tests/cpp/test_integration_pcap_format[1]_tests.cmake")
else()
  add_test(test_integration_pcap_format_NOT_BUILT test_integration_pcap_format_NOT_BUILT)
endif()
