if(EXISTS "/path/to/asterix/tests/cpp/test_category[1]_tests.cmake")
  include("/path/to/asterix/tests/cpp/test_category[1]_tests.cmake")
else()
  add_test(test_category_NOT_BUILT test_category_NOT_BUILT)
endif()
