add_test([=[CAT048IntegrationTest.LoadXMLConfiguration]=]  /path/to/asterix/bin/test_integration_cat048 [==[--gtest_filter=CAT048IntegrationTest.LoadXMLConfiguration]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CAT048IntegrationTest.LoadXMLConfiguration]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CAT048IntegrationTest.ParseCAT048BinaryData]=]  /path/to/asterix/bin/test_integration_cat048 [==[--gtest_filter=CAT048IntegrationTest.ParseCAT048BinaryData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CAT048IntegrationTest.ParseCAT048BinaryData]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CAT048IntegrationTest.VerifyParsedDataStructure]=]  /path/to/asterix/bin/test_integration_cat048 [==[--gtest_filter=CAT048IntegrationTest.VerifyParsedDataStructure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CAT048IntegrationTest.VerifyParsedDataStructure]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CAT048IntegrationTest.RejectInvalidData]=]  /path/to/asterix/bin/test_integration_cat048 [==[--gtest_filter=CAT048IntegrationTest.RejectInvalidData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CAT048IntegrationTest.RejectInvalidData]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CAT048IntegrationTest.VerifyTextOutput]=]  /path/to/asterix/bin/test_integration_cat048 [==[--gtest_filter=CAT048IntegrationTest.VerifyTextOutput]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CAT048IntegrationTest.VerifyTextOutput]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_integration_cat048_TESTS CAT048IntegrationTest.LoadXMLConfiguration CAT048IntegrationTest.ParseCAT048BinaryData CAT048IntegrationTest.VerifyParsedDataStructure CAT048IntegrationTest.RejectInvalidData CAT048IntegrationTest.VerifyTextOutput)
