if(EXISTS "/home/e/Development/asterix/tests/cpp/test_dataitemformatbds[1]_tests.cmake")
  include("/home/e/Development/asterix/tests/cpp/test_dataitemformatbds[1]_tests.cmake")
else()
  add_test(test_dataitemformatbds_NOT_BUILT test_dataitemformatbds_NOT_BUILT)
endif()
