add_test([=[InputParserTest.ConstructorWithDefinition]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ConstructorWithDefinition]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ConstructorWithDefinition]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseSingleBlockPacket]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseSingleBlockPacket]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseSingleBlockPacket]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseMultipleConsecutivePackets]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseMultipleConsecutivePackets]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseMultipleConsecutivePackets]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseTruncatedPacket]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseTruncatedPacket]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseTruncatedPacket]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseInvalidLength]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseInvalidLength]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseInvalidLength]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseZeroLength]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseZeroLength]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseZeroLength]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseLengthExceedsBuffer]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseLengthExceedsBuffer]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseLengthExceedsBuffer]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseEmptyBuffer]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseEmptyBuffer]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseEmptyBuffer]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseSingleByte]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseSingleByte]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseSingleByte]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseTwoBytes]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseTwoBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseTwoBytes]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseThreeBytesMinimum]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseThreeBytesMinimum]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseThreeBytesMinimum]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseDifferentCategories]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseDifferentCategories]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseDifferentCategories]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseUndefinedCategory]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseUndefinedCategory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseUndefinedCategory]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParsePacketWithTimestamp]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParsePacketWithTimestamp]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParsePacketWithTimestamp]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseNextDataBlock]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseNextDataBlock]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseNextDataBlock]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseNextDataBlockInvalidLength]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseNextDataBlockInvalidLength]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseNextDataBlockInvalidLength]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseNextDataBlockLengthExceeds]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseNextDataBlockLengthExceeds]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseNextDataBlockLengthExceeds]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.PrintDefinition]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.PrintDefinition]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.PrintDefinition]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.FilterOutItem]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.FilterOutItem]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.FilterOutItem]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.IsFiltered]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.IsFiltered]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.IsFiltered]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseLargePacket]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseLargePacket]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseLargePacket]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParsePacketWithFormatError]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParsePacketWithFormatError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParsePacketWithFormatError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParsePacketContinuesAfterError]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParsePacketContinuesAfterError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParsePacketContinuesAfterError]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseMaximumLength]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseMaximumLength]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseMaximumLength]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseCategoryZero]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseCategoryZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseCategoryZero]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InputParserTest.ParseCategory255]=]  /path/to/asterix/bin/test_inputparser [==[--gtest_filter=InputParserTest.ParseCategory255]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InputParserTest.ParseCategory255]=]  PROPERTIES WORKING_DIRECTORY /path/to/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_inputparser_TESTS InputParserTest.ConstructorWithDefinition InputParserTest.ParseSingleBlockPacket InputParserTest.ParseMultipleConsecutivePackets InputParserTest.ParseTruncatedPacket InputParserTest.ParseInvalidLength InputParserTest.ParseZeroLength InputParserTest.ParseLengthExceedsBuffer InputParserTest.ParseEmptyBuffer InputParserTest.ParseSingleByte InputParserTest.ParseTwoBytes InputParserTest.ParseThreeBytesMinimum InputParserTest.ParseDifferentCategories InputParserTest.ParseUndefinedCategory InputParserTest.ParsePacketWithTimestamp InputParserTest.ParseNextDataBlock InputParserTest.ParseNextDataBlockInvalidLength InputParserTest.ParseNextDataBlockLengthExceeds InputParserTest.PrintDefinition InputParserTest.FilterOutItem InputParserTest.IsFiltered InputParserTest.ParseLargePacket InputParserTest.ParsePacketWithFormatError InputParserTest.ParsePacketContinuesAfterError InputParserTest.ParseMaximumLength InputParserTest.ParseCategoryZero InputParserTest.ParseCategory255)
