if(EXISTS "/path/to/asterix/tests/cpp/test_asterixdefinition[1]_tests.cmake")
  include("/path/to/asterix/tests/cpp/test_asterixdefinition[1]_tests.cmake")
else()
  add_test(test_asterixdefinition_NOT_BUILT test_asterixdefinition_NOT_BUILT)
endif()
