if(EXISTS "/path/to/asterix/tests/cpp/test_dataitemformatfixed[1]_tests.cmake")
  include("/path/to/asterix/tests/cpp/test_dataitemformatfixed[1]_tests.cmake")
else()
  add_test(test_dataitemformatfixed_NOT_BUILT test_dataitemformatfixed_NOT_BUILT)
endif()
