add_test([=[UAPItemTest.DefaultConstructorInitialization]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.DefaultConstructorInitialization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.DefaultConstructorInitialization]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.MembersCanBeSet]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.MembersCanBeSet]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.MembersCanBeSet]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.CopyConstructorCopiesAllFields]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.CopyConstructorCopiesAllFields]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.CopyConstructorCopiesAllFields]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.CopyIsIndependent]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.CopyIsIndependent]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.CopyIsIndependent]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.CloneCreatesIndependentCopy]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.CloneCreatesIndependentCopy]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.CloneCreatesIndependentCopy]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.CAT048_010DataSourceIdentifier]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.CAT048_010DataSourceIdentifier]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.CAT048_010DataSourceIdentifier]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.FXFlagSet]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.FXFlagSet]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.FXFlagSet]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.VariousBitPositions]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.VariousBitPositions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.VariousBitPositions]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.CAT062_010DataSourceIdentifier]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.CAT062_010DataSourceIdentifier]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.CAT062_010DataSourceIdentifier]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.DestructorWorks]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.DestructorWorks]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.DestructorWorks]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.VariableLengthItem]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.VariableLengthItem]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.VariableLengthItem]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.LargeFRNValue]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.LargeFRNValue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.LargeFRNValue]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.CopyConstructorEmptyItemID]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.CopyConstructorEmptyItemID]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.CopyConstructorEmptyItemID]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.MaximumFieldValues]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.MaximumFieldValues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.MaximumFieldValues]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.CAT048TypicalItems]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.CAT048TypicalItems]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.CAT048TypicalItems]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.MultipleClones]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.MultipleClones]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.MultipleClones]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.CreateDestroyLoop]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.CreateDestroyLoop]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.CreateDestroyLoop]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.ItemIDWithSpecialCharacters]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.ItemIDWithSpecialCharacters]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.ItemIDWithSpecialCharacters]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.CopyConstructorWithParentFormat]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.CopyConstructorWithParentFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.CopyConstructorWithParentFormat]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.SafeDefaultValues]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.SafeDefaultValues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.SafeDefaultValues]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.SecondFSPECOctetBitPositions]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.SecondFSPECOctetBitPositions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.SecondFSPECOctetBitPositions]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.FXItemFirstOctet]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.FXItemFirstOctet]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.FXItemFirstOctet]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.FXItemSecondOctet]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.FXItemSecondOctet]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.FXItemSecondOctet]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.ZeroLengthItem]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.ZeroLengthItem]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.ZeroLengthItem]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UAPItemTest.BaseClassConstructorChain]=]  /home/e/Development/asterix/bin/test_uapitem [==[--gtest_filter=UAPItemTest.BaseClassConstructorChain]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UAPItemTest.BaseClassConstructorChain]=]  PROPERTIES WORKING_DIRECTORY /home/e/Development/asterix/tests/cpp SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_uapitem_TESTS UAPItemTest.DefaultConstructorInitialization UAPItemTest.MembersCanBeSet UAPItemTest.CopyConstructorCopiesAllFields UAPItemTest.CopyIsIndependent UAPItemTest.CloneCreatesIndependentCopy UAPItemTest.CAT048_010DataSourceIdentifier UAPItemTest.FXFlagSet UAPItemTest.VariousBitPositions UAPItemTest.CAT062_010DataSourceIdentifier UAPItemTest.DestructorWorks UAPItemTest.VariableLengthItem UAPItemTest.LargeFRNValue UAPItemTest.CopyConstructorEmptyItemID UAPItemTest.MaximumFieldValues UAPItemTest.CAT048TypicalItems UAPItemTest.MultipleClones UAPItemTest.CreateDestroyLoop UAPItemTest.ItemIDWithSpecialCharacters UAPItemTest.CopyConstructorWithParentFormat UAPItemTest.SafeDefaultValues UAPItemTest.SecondFSPECOctetBitPositions UAPItemTest.FXItemFirstOctet UAPItemTest.FXItemSecondOctet UAPItemTest.ZeroLengthItem UAPItemTest.BaseClassConstructorChain)
