/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: AsterixData.idl
  Source: AsterixData.hpp
  Cyclone DDS: v0.10.4

*****************************************************************/
#ifndef DDSCXX_ASTERIXDATA_HPP
#define DDSCXX_ASTERIXDATA_HPP

#include <cstdint>
#include <vector>

namespace AsterixDDS
{
class AsterixPayload
{
private:
 std::vector<uint8_t> data_;
 uint16_t category_ = 0;
 uint64_t timestamp_ = 0;

public:
  AsterixPayload() = default;

  explicit AsterixPayload(
    const std::vector<uint8_t>& data,
    uint16_t category,
    uint64_t timestamp) :
    data_(data),
    category_(category),
    timestamp_(timestamp) { }

  const std::vector<uint8_t>& data() const { return this->data_; }
  std::vector<uint8_t>& data() { return this->data_; }
  void data(const std::vector<uint8_t>& _val_) { this->data_ = _val_; }
  void data(std::vector<uint8_t>&& _val_) { this->data_ = _val_; }
  uint16_t category() const { return this->category_; }
  uint16_t& category() { return this->category_; }
  void category(uint16_t _val_) { this->category_ = _val_; }
  uint64_t timestamp() const { return this->timestamp_; }
  uint64_t& timestamp() { return this->timestamp_; }
  void timestamp(uint64_t _val_) { this->timestamp_ = _val_; }

  bool operator==(const AsterixPayload& _other) const
  {
    (void) _other;
    return data_ == _other.data_ &&
      category_ == _other.category_ &&
      timestamp_ == _other.timestamp_;
  }

  bool operator!=(const AsterixPayload& _other) const
  {
    return !(*this == _other);
  }

};

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::AsterixDDS::AsterixPayload>::getTypeName()
{
  return "AsterixDDS::AsterixPayload";
}

template <> constexpr bool TopicTraits<::AsterixDDS::AsterixPayload>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::AsterixDDS::AsterixPayload>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::AsterixDDS::AsterixPayload>::type_map_blob_sz() { return 302; }
template<> constexpr unsigned int TopicTraits<::AsterixDDS::AsterixPayload>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::AsterixDDS::AsterixPayload>::type_map_blob() {
  static const uint8_t blob[] = {
 0x5f,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xb7,  0xd6,  0x88,  0x56,  0xd7,  0xa2,  0x7c,
 0xbc,  0x67,  0x34,  0xa5,  0xda,  0xb5,  0xdd,  0x00,  0x47,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00,
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x37,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,
 0x10,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x02,
 0x8d,  0x77,  0x7f,  0x38,  0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x06,  0xc4,
 0xef,  0x35,  0x2f,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0xd7,
 0xe6,  0xd5,  0x5b,  0x00,  0xa0,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x53,  0xf5,  0xbf,
 0x80,  0x3e,  0xd4,  0x6a,  0xa9,  0x5e,  0x29,  0x74,  0x5b,  0x6a,  0xd3,  0x00,  0x88,  0x00,  0x00,  0x00,
 0xf2,  0x51,  0x01,  0x00,  0x23,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1b,  0x00,  0x00,  0x00,
 0x41,  0x73,  0x74,  0x65,  0x72,  0x69,  0x78,  0x44,  0x44,  0x53,  0x3a,  0x3a,  0x41,  0x73,  0x74,  0x65,
 0x72,  0x69,  0x78,  0x50,  0x61,  0x79,  0x6c,  0x6f,  0x61,  0x64,  0x00,  0x00,  0x58,  0x00,  0x00,  0x00,
 0x03,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,
 0x01,  0x00,  0x00,  0x02,  0x05,  0x00,  0x00,  0x00,  0x64,  0x61,  0x74,  0x61,  0x00,  0x00,  0x00,  0x00,
 0x17,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x06,  0x00,  0x09,  0x00,  0x00,  0x00,
 0x63,  0x61,  0x74,  0x65,  0x67,  0x6f,  0x72,  0x79,  0x00,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,
 0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x74,  0x69,  0x6d,  0x65,
 0x73,  0x74,  0x61,  0x6d,  0x70,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,
 0xf2,  0x53,  0xf5,  0xbf,  0x80,  0x3e,  0xd4,  0x6a,  0xa9,  0x5e,  0x29,  0x74,  0x5b,  0x6a,  0xd3,  0xf1,
 0xb7,  0xd6,  0x88,  0x56,  0xd7,  0xa2,  0x7c,  0xbc,  0x67,  0x34,  0xa5,  0xda,  0xb5,  0xdd, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::AsterixDDS::AsterixPayload>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00,
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xb7,  0xd6,  0x88,  0x56,  0xd7,  0xa2,  0x7c,  0xbc,  0x67,  0x34,  0xa5,
 0xda,  0xb5,  0xdd,  0x00,  0x4b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00,
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x53,  0xf5,  0xbf,  0x80,  0x3e,  0xd4,  0x6a,  0xa9,  0x5e,  0x29,  0x74,
 0x5b,  0x6a,  0xd3,  0x00,  0x8c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::AsterixDDS::AsterixPayload>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::AsterixDDS::AsterixPayload>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::AsterixDDS::AsterixPayload)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::AsterixDDS::AsterixPayload>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::AsterixDDS::AsterixPayload& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.data().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.category()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.timestamp()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::AsterixDDS::AsterixPayload& instance, bool as_key) {
  auto &props = get_type_props<::AsterixDDS::AsterixPayload>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data());
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::AsterixDDS::AsterixPayload& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.data().size());
      if (!read(streamer, se_1))
        return false;
      instance.data().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.category()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.timestamp()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::AsterixDDS::AsterixPayload& instance, bool as_key) {
  auto &props = get_type_props<::AsterixDDS::AsterixPayload>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data());
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::AsterixDDS::AsterixPayload& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.data().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.category()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.timestamp()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::AsterixDDS::AsterixPayload& instance, bool as_key) {
  auto &props = get_type_props<::AsterixDDS::AsterixPayload>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data());
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::AsterixDDS::AsterixPayload& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.category()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.timestamp()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::AsterixDDS::AsterixPayload& instance, bool as_key) {
  auto &props = get_type_props<::AsterixDDS::AsterixPayload>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data());
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_ASTERIXDATA_HPP
