# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in asterix.gemspec
gemspec

group :development, :test do
  gem 'pry', '~> 0.14'
  gem 'pry-byebug', '~> 3.10'
end

group :test do
  gem 'codecov', '~> 0.6', require: false
end
